//--------------------------------------------------------------------------
//
// ScriptName : AriRenamer
// Contents   : 複数のノードをテキストエディタ感覚でリネームします。
// Author     : Ari
// Help       : http://cgjishu.net/blog-entry-42.html
// Since      : 2014/08
// LastUpdate : 2020/11/15 Maya2019に対応するShapeRenameの項目を追加
//              2020/10/11 Type選択機能追加
//                         英語UI追加等
//              2019/02/11 ページ機能追加 連番機能追加 等
//              2017/12/06 アンダーバーで始まるノード名等ををエラーと判断したので修正
//              2017/01/29 一括変更、連番挿入をしやすいようにUIを少し変更。
//                         アルファベット連番機能追加。
//              2016/04/10 複数のオブジェクトが名前と一致エラーを回避
//                         複数のfileノードが同じテクスチャを参照している場合のエラーを回避
//              2016/01/25 fileノードが参照するテクスチャファイルの名前を変更する機能を追加。
//              2015/08/23 fileノードのパスをリネームする機能を追加。
//              2015/06/24 条件機能:末尾数字の桁数を統一する機能を追加。
//              2015/06/09 結果非表示の場合のバグ修正。
//              2015/06/07 Shapeノードも取得できるように変更。
//                         条件機能:Shapeノードを親ノードから予測できる通常名にするを追加。
//                         条件機能:語尾の数字を消すを追加。
//              2015/05/11 「追加」「削除」機能を追加
//              2015/03/16 検索取得機能修正。(同名があった場合親の名前も拾ってしまったものを修正)
//              2015/03/15 検索取得機能追加。
//                         条件リネーム(:前方削除、fileノードテクスチャ名取得)追加。
//                         リザルト表示改良。
//                         デフォルト名リネーム回避。
//              2015/01/15 リザルト表示追加。
//                         リストからオブジェクト選択機能追加。
//              2014/11/24 連番の入力数値を保持
//              2014/11/02 連番、置換、挿入などの機能を追加。かなり改造。改バージョン公開。
//              -----------------------------------------------------------
//              2014/08/12 エラー回避(グループの深い階層からリネーム)
//              2014/08    旧リネーマー公開
//
//--------------------------------------------------------------------------



proc string GetType(string $node)
{
	global string $AriRename_UI_ShapeCB;
	int $shapeTrue =`checkBox -q -v $AriRename_UI_ShapeCB`;
	string $getType = `nodeType $node`;
	string $type = $getType;
	if($shapeTrue == false){
		if($getType == "transform"){
			string $shape[] =`listRelatives -c -s -pa $node`;
			string $shapeType;
			if($shape[0] != ""){
				$shapeType = `nodeType $shape[0]`;
			}
			else{
				$shapeType = "group";
			}
			$type = $shapeType;
		}
	}
	return $type;
}
proc string[] GetTypeList(string $nodeList[])
{
	string $typeList[];
	clear $typeList;
	for($node in $nodeList){
		$type = GetType($node);
		if(!stringArrayContains($type, $typeList)){
			$typeList[size($typeList)] = $type;
		}
	}
	return $typeList;
}
proc AriRenamer_TypeListPop(){
	global string $AriRenamer_getList_all[];         
	global string $AriRenamer_UI_TypePop;
	string $typeList[] = GetTypeList($AriRenamer_getList_all);
	popupMenu -e -dai $AriRenamer_UI_TypePop;
	for($type in $typeList){
		string $icon = ("out_"+$type+".png");
		if($type == "group")$icon = "out_transform.png";
		menuItem -p $AriRenamer_UI_TypePop  -l $type -i $icon -c ("AriRenamer_NodeTypeReload(\""+$type+"\")");
	}
	menuItem -p $AriRenamer_UI_TypePop -divider true;
	menuItem -p $AriRenamer_UI_TypePop  -l "all" -c ("AriRenamer_NodeTypeReload(\"all\")");
}
proc ArrayTextScrollList(string $textList[],string $textScrollListUI){
	string $text;
	for($i=0; $i<size($textList); $i++){
		if($textList[$i]!=""){
			$text = ($text+" -a \""+$textList[$i]+"\"");
		}
	}
	eval("textScrollList -e  -removeAll   "+$text+" "+ $textScrollListUI);
}
proc int ArrayChangeCheck(string $textListA[],string $textListB[]){
	if(size($textListA)!=size($textListB))return 0;
	int $noChange = true;
	for($i=0; $i<size($textListA); $i++){
		if($textListA[$i]!=$textListB[$i]){
			$noChange = false;
			break;
		}	
	}
	return $noChange;
}
proc string[] AriRenamer_textToArray(string $text){
	string $array[];
	string $beforeString = "\n\n";
	string $afterString  = "\n%\n";
	int $strSize=size($beforeString);
	int $k=0;
	for($j=1;$j<size($text)-$strSize+2;$j++){
		string $sub=substring ($text,$j,$j-1+$strSize);
		if($sub==$beforeString){
			$text=	startString($text,$j-1)
						+$afterString
						+endString($text,size($text)-($j-1+$strSize));
			$j=$j+(size($afterString)-3);
		}
		$k++;
		if($k>10000)break;
	}
	tokenize $text "\n" $array;
	int $i=0;
	for($i=0;$i<size($array);$i++){
		if($array[$i]=="%")$array[$i]="";
	}
	if(size($array)==1 && $array[0]=="")clear $array;
	return $array;
}
proc string AriRenamer_ShortName(string $name){
	string $sepa[];
	tokenize $name "|" $sepa;
	return $sepa[size($sepa)-1];
}
proc string AriRenamer_ToText(string $textList[],int $mode){
	string $exText;
	int $amount = 0;
	int $maxText = size($textList);
	for($text in $textList){
		if($mode==0)$text=AriRenamer_ShortName($text);
		$exText=($exText+$text+"\n");
	}
	return $exText;
}
proc string[] AriRenamer_DeleteType(string $nameList[],string $type){
	string $refreshList[];
	int $j=0;
	for($i=0;$i<size($nameList);$i++){
		if (!`objectType -isType $type $nameList[$i]`){
			$refreshList[$j]=$nameList[$i];
			$j++;
		}
	}
	return $refreshList;
}
proc string[] AriRenamer_NumberSeparate(string $beforeName,int $mode){
	string $afterName[];
	int $nameSize=size($beforeName);
	int $breakNum1=0;
	int $breakNum2=0;
	for($i=0;$i<$nameSize;$i++){
		string $end=(substring($beforeName , $nameSize-$i ,$nameSize-$i));		
		if(`gmatch $end ("[0-9]")`){
			$breakNum1 = $i+1;
		}
		else{
			break;
		}
		if(`gmatch $end ("[1-9]")`){
			$breakNum2 = $i+1;
		}
	}
	string $stringString;
	string $stringNumber;
	if($mode==0){
		$stringString=startString ($beforeName,$nameSize-$breakNum1);
	    $stringNumber=endString ($beforeName,$breakNum1);
	}
	if($mode==1){
		$stringString=startString ($beforeName,$nameSize-$breakNum2);
	    $stringNumber=endString ($beforeName,$breakNum2);
	}
	$afterName[0]=$stringString;
	$afterName[1]= $stringNumber;
	return $afterName;
}
proc int AriRenamer_unRenameNode(string $name){
	int $unRenameTrue=0;
	string $unRenameNode[]={
			 "time1", 
			 "sequenceManager1", 
			 "renderPartition", 
			 "renderGlobalsList1", 
			 "defaultLightList1", 
			 "defaultShaderList1", 
			 "postProcessList1", 
			 "defaultRenderUtilityList1", 
			 "defaultRenderingList1", 
			 "lightList1", 
			 "defaultTextureList1", 
			 "lambert1", 
			 "particleCloud1", 
			 "initialShadingGroup", 
			 "initialParticleSE", 
			 "initialMaterialInfo", 
			 "shaderGlow1", 
			 "dof1", 
			 "defaultRenderGlobals", 
			 "defaultRenderQuality", 
			 "defaultResolution", 
			 "defaultLightSet", 
			 "defaultObjectSet", 
			 "defaultViewColorManager", 
			 "hardwareRenderGlobals", 
			 "hardwareRenderingGlobals", 
			 "characterPartition", 
			 "defaultHardwareRenderGlobals", 
			 "ikSystem", 
			 "hyperGraphInfo", 
			 "hyperGraphLayout", 
			 "globalCacheControl", 
			 "strokeGlobals", 
			 "dynController1", 
			 "persp", 
			 "perspShape", 
			 "top", 
			 "topShape", 
			 "front", 
			 "frontShape", 
			 "side", 
			 "sideShape", 
			 "lightLinker1", 
			 "DefaultMaterialsAndShaderGlowFilter7", 
			 "selectionListOperator84", 
			 "DefaultMaterialsFilter9", 
			 "DefaultShaderGlowFilter9", 
			 "objectTypeFilter96", 
			 "layerManager", 
			 "defaultLayer", 
			 "renderLayerManager", 
			 "defaultRenderLayer"
	};
	$unRenameTrue=stringArrayContains($name,$unRenameNode);
	return $unRenameTrue;
}
proc int getGlobalNum(int $localNum){
	global string $AriRenamer_UI_viewTotalIF;
	global int $AriRenamer_value_nowpage;
	int $page = $AriRenamer_value_nowpage;
	int $viewTotal = `intField -q -v $AriRenamer_UI_viewTotalIF`; 
	int $num = $viewTotal * ($page-1)+$localNum;
	return $num;
}
proc int getLocalNum(int $globalNum){
	global string $AriRenamer_UI_viewTotalIF;
	global int $AriRenamer_value_nowpage;
	int $page = $AriRenamer_value_nowpage;
	int $viewTotal = `intField -q -v $AriRenamer_UI_viewTotalIF`; 
	int $num = $globalNum - $viewTotal * ($page-1);
	return $num;
}
proc int[] AriRenamer_getLeftSelectNumber(){
	global string $AriRenamer_UI_baseNameTextField;
	global string $AriRenamer_UI_baseNameTreeView;
	global string $AriRenamer_UI_pageNow_IF;
	global string $AriRenamer_UI_viewTotalIF;
	int $nowPage   = `intSliderGrp -q -v $AriRenamer_UI_pageNow_IF`;
	int $viewTotal = `intField -q -v $AriRenamer_UI_viewTotalIF`;
	int $selectNum[];
	int $getNum[] = `textScrollList -q -sii $AriRenamer_UI_baseNameTextField`;
	for($i=0; $i<size($getNum); $i++){
		$selectNum[$i] = $getNum[$i] + (($nowPage-1)*$viewTotal);
	}
	/*
	string $selectList[] = `treeView -q -selectItem $AriRenamer_UI_baseNameTreeView`; 
	string $allList[]    = `treeView -q -ch ""      $AriRenamer_UI_baseNameTreeView`; 
	clear $getNum;
	for($i=0; $i<size($allList); $i++){
		if(stringArrayContains($allList[$i],$selectList)){
			$getNum[size($getNum)] = $i+1;
		}
	}
	for($i=0; $i<size($getNum); $i++){
		$selectNum[$i] = getGlobalNum($getNum[$i]);
	}
	*/
	return $selectNum;
}
proc string[] AriRenamer_getLeftSelectName(){
	global string $AriRenamer_UI_baseNameTextField;
	global string $AriRenamer_UI_baseNameTreeView;
	string $selectList[];
	$selectList = `textScrollList -q -si $AriRenamer_UI_baseNameTextField`;
	return $selectList;
}
proc string[] AriRenamer_readLeftField(){
	global string $AriRenamer_getList_processing[];  
	global string $AriRename_modeValue;
	global string $AriRenamer_UI_baseNameTreeView;
	global string $AriRenamer_UI_baseNameTextField;
	global string $AriRenamer_UI_viewTotalIF;
	global string $AriRenamer_UI_pageNow_IF;
	int $mode = 0;
	$mode = `intField -q -v $AriRename_modeValue`;
	int $viewTotal = `intField -q -v $AriRenamer_UI_viewTotalIF`;
	int $pageNow   = `intSliderGrp -q -v $AriRenamer_UI_pageNow_IF`;
	string $getList[];
	if($mode == 3)	$getList = `treeView       -q -ch "" $AriRenamer_UI_baseNameTreeView`; 
	else			$getList = `textScrollList -q -ai    $AriRenamer_UI_baseNameTextField`;
	string $arrayText[] = $AriRenamer_getList_processing;
	/*
	for($i=0; $i<size($getList); $i++){
		int $num = $i + ($pageNow-1) * $viewTotal;
		$arrayText[$i] = $getList[$num];
	}
	*/
	return $arrayText;
}
proc AriRenamer_writeleftField(){
	global string $AriRenamer_getList_processing[];  
	global string $AriRenamer_UI_baseNameTextField; 
	global string $AriRenamer_UI_baseNameTreeView;  
	global string $AriRenamer_UI_totalTF[4];
	global string $AriRenamer_UI_viewTotalIF;
	global string $AriRenamer_UI_pageNow_IF;
	textScrollList -e -ra $AriRenamer_UI_baseNameTextField; 
	treeView -e -ra              $AriRenamer_UI_baseNameTreeView;
	treeView -e -nb 1 -arp false $AriRenamer_UI_baseNameTreeView;
	if(size($AriRenamer_getList_processing)==0){
		textField -e -text "0" $AriRenamer_UI_totalTF[0];
		return;
	}
	int $pageNow   = `intSliderGrp -q -v $AriRenamer_UI_pageNow_IF`;
	int $viewTotal = `intField     -q -v $AriRenamer_UI_viewTotalIF`;
	for($i=0; $i<$viewTotal; $i++){
		int $num = $i + ($pageNow-1)*$viewTotal;
		if($AriRenamer_getList_processing[$num]=="")break;
		textScrollList -e -a $AriRenamer_getList_processing[$num] $AriRenamer_UI_baseNameTextField;
		treeView -e -addItem      $AriRenamer_getList_processing[$num] ""          $AriRenamer_UI_baseNameTreeView; 
	}
	int $size = size($AriRenamer_getList_processing);
	textField -e -text $size $AriRenamer_UI_totalTF[0];
}
proc string[] AriRenamer_readScrollField(){
	global int $AriRenamer_value_nowpage;
	global int $AriRenamer_value_viewTotal; 
	global string $AriRenamer_nameList_rename[];
	global string $AriRenamer_UI_targetNameTextField;
	global string $AriRenamer_UI_viewTotalIF;
	global string $AriRenamer_UI_pageNow_IF;
	int $viewTotal = $AriRenamer_value_viewTotal;
	int $pageNow   = $AriRenamer_value_nowpage;
	string $getText   = `scrollField -q -text $AriRenamer_UI_targetNameTextField`;
	string $getList[] = AriRenamer_textToArray($getText);
	string $arrayText[] = $AriRenamer_nameList_rename;
	for($i=0; $i<size($getList); $i++){
		int $num = $i + ($pageNow-1) * $viewTotal;
		$arrayText[$num] = $getList[$i];
	}
	return $arrayText;
}
proc AriRenamer_writeHistory(string $writeText){
	global string $AriRename_History[50];
	if($AriRename_History[0]==$writeText)return;
	for($i=size($AriRename_History);$i>0;$i--){
		if($i<50)	$AriRename_History[$i]=$AriRename_History[$i-1];
	}
	$AriRename_History[0] = $writeText;
}
proc AriRenamer_writeScrollField(string $getList[],int $historyMode){
	global string $AriRenamer_nameList_rename[];
	global string $AriRename_History[50];
	global string $AriRenamer_UI_targetNameTextField;
	global string $AriRenamer_UI_viewTotalIF;
	global string $AriRenamer_UI_pageNow_IF;
	string $nowTextList[] = AriRenamer_readScrollField();
	string $nowtext       = AriRenamer_ToText($nowTextList,0);
	string $writeText     = AriRenamer_ToText($getList,0); 
	int $viewTotal = `intField     -q -v $AriRenamer_UI_viewTotalIF`;
	int $pageNow   = `intSliderGrp -q -v $AriRenamer_UI_pageNow_IF`; 
	clear $AriRenamer_nameList_rename;
	for($i=0; $i<size($getList); $i++){
		$AriRenamer_nameList_rename[$i] = AriRenamer_ShortName($getList[$i]);
	}
	string $viewText = "";
	for($i=0; $i<$viewTotal; $i++){
		int $num = $i + ($pageNow-1)*$viewTotal;
		if($AriRenamer_nameList_rename[$num]=="")continue;
		$viewText = ($viewText + $AriRenamer_nameList_rename[$num] +"\n");
	}
	scrollField -e -text $viewText $AriRenamer_UI_targetNameTextField;
	if($historyMode == 1){
		if($nowtext!=$writeText || $nowtext!=""){
			AriRenamer_writeHistory($nowtext);
		}
		AriRenamer_writeHistory($writeText);
	}
	if($historyMode == 3){
		AriRenamer_writeHistory($writeText);
	}
	if($historyMode == 0){
		clear $AriRename_History;
		$AriRename_History[0] = $writeText;
	}
}
global proc int[] AriRenamer_CursorPos(){
	global string $AriRenamer_UI_viewTotalIF;
	global string $AriRenamer_UI_targetNameTextField;
	int $localPos[2];
	int $viewTotal = `intField -q -v $AriRenamer_UI_viewTotalIF`;
	int $globalPos= `scrollField -q -ip $AriRenamer_UI_targetNameTextField`;
	string $textList[] = AriRenamer_readScrollField();
	int $work = $globalPos;
	int $j=1;
	for($i=0; $i<$viewTotal; $i++){
		int $num = getGlobalNum($i);
		$text = $textList[$num];
		$work = $work - size($text)-1;
		if($work<0){
			$localPos[1] = $work+size($text);
			$localPos[0] = $i+1;
			if($localPos[1]==-1){
				$localPos[0] = $localPos[0]-1;
				$localPos[1] = size($textList[$num-1]);
			}
			break;
		}
	}
	if($localPos[0]==0){
		$localPos[0] = size($textList);
		if($localPos[0]!=0){
			int $num = getGlobalNum($i);
			$localPos[1] = size($textList[$num]);
		}
	}
	return $localPos;
}
global proc AriRenamer_CursorPosMove(int $y,int $x){
	global int $AriRenamer_value_nowpage;
	global int $AriRenamer_value_viewTotal;
	global string $AriRenamer_UI_viewTotalIF;
	global string $AriRenamer_UI_targetNameTextField;
	int $globalPos = 0;
	int $viewTotal = $AriRenamer_value_viewTotal;
	int $page = $AriRenamer_value_nowpage;
	string $textList[] = AriRenamer_readScrollField();
	int $total=1;
	int $i=0;
	while($i < $y-1){
		int $num = $viewTotal*($page-1)+$i;
		$total = $total + size($textList[$num]) + 1;
		$i++;
	}
	$globalPos = $total+$x;
	scrollField -e -ip $globalPos $AriRenamer_UI_targetNameTextField;
}
global proc AriRenamer_PageChange(int $mode){
	global int $AriRenamer_value_nowpage;   
	global int $AriRenamer_value_viewTotal; 
	global string $AriRenamer_getList_processing[]; 
	global string $AriRenamer_nameList_rename[];     
	global string $AriRenamer_UI_viewTotalIF; 
	global string $AriRenamer_UI_pageNow_IF;  
	global string $AriRenamer_UI_pageTotal_IF;
	string $nowTextList[] = AriRenamer_readScrollField();
	int $viewTotal = `intField     -q -v $AriRenamer_UI_viewTotalIF`;
	int $nowPage   = `intSliderGrp -q -v $AriRenamer_UI_pageNow_IF`;
	int $getTotal  =  size($AriRenamer_getList_processing);
	int $pageTotal =  $getTotal / $viewTotal;
	if($getTotal % $viewTotal !=0)$pageTotal++;
	if($mode==1)$nowPage = $nowPage+1;
	if($mode==2)$nowPage = $nowPage-1;
	if($mode==4)$nowPage = 1;
	if($mode==3)$nowPage = $pageTotal;
	if($nowPage<1)$nowPage=1;
	if($pageTotal<1)$pageTotal=1;
	if($nowPage>$pageTotal)$nowPage=$pageTotal;
	int $sliderTrue = false;
	float $sliderColor = 0.3;
	if($pageTotal>1){
		$sliderTrue = true;
		$sliderColor = 0.4;
	}
	global string $AriRenamer_UI_pageChangeRow;
	rowLayout -e -en $sliderTrue $AriRenamer_UI_pageChangeRow;
	if($sliderTrue)	rowLayout -e -bgc 0.4 0.4 0.4 $AriRenamer_UI_pageChangeRow;
	else 			rowLayout -e -bgc 0.1 0.1 0.1 $AriRenamer_UI_pageChangeRow;
	intSliderGrp -e -en $sliderTrue -v $nowPage -max $pageTotal $AriRenamer_UI_pageNow_IF;
	$AriRenamer_value_nowpage   = $nowPage;
	$AriRenamer_value_viewTotal = $viewTotal;
	AriRenamer_writeleftField();
	AriRenamer_writeScrollField($nowTextList,3);
	intField -e -v ($pageTotal) $AriRenamer_UI_pageTotal_IF;
	AriRenamer_ObjSelect();
	optionVar -iv "AriRenamerViewTotal" $AriRenamer_value_viewTotal;
	AriRenamer_LeftSelect(0);
}
global proc AriRenamer_NodeTypeReload(string $type){
	global string $AriRenamer_getList_all[];         
	global string $AriRenamer_getList_processing[];  
	global string $AriRenamer_nameList_rename[];
	global string $AriRename_History[];
	global string $AriRename_ReHistory[];
	global string $AriRename_modeValue;
	string $viewTypeList[] = {};
	$viewTypeList[0] = $type;
	if($viewTypeList[0]=="all"){
		clear $viewTypeList;
	}
	clear $AriRename_History;
	clear $AriRename_ReHistory;
	if(size($viewTypeList)==0){
		$AriRenamer_getList_processing = $AriRenamer_getList_all;
	}
	else{
		string $processList[];
		clear $processList;
		for($name in $AriRenamer_getList_all){
			string $type = GetType($name);
			if(stringArrayContains($type,$viewTypeList)){
				$processList[size($processList)] = $name;
			}
		}
		clear $AriRenamer_getList_processing;
		$AriRenamer_getList_processing = $processList;
	}
	AriRenamer_writeleftField();
	string $newRightList[] = $AriRenamer_getList_processing;
	int $renameMode = 0;
	$renameMode  = `intField -q -v $AriRename_modeValue`;
	if($renameMode==0){
		AriRenamer_writeScrollField($newRightList,0);
	}
	if($renameMode==1 || $renameMode==2){
		string $pathList[];
		int $i=0;
		for($file in $newRightList){
			$pathList[$i] = `getAttr ($file+".fileTextureName")`;
			if($renameMode==2){
				string $sepa[];
				tokenize $pathList[$i] "/" $sepa;
				$pathList[$i] = $sepa[size($sepa)-1];
			}
			$i++;
		}
		AriRenamer_writeScrollField($pathList,0);
	}
	if($renameMode==4){
		string $attrName = "preFilterRadius";
		string $valueList[];
		int $i=0;
		for($obj in $newRightList){
			if(attributeExists($attrName,$obj)){
				$valueList[$i] = `getAttr ($obj + "." + $attrName)`;
			}
			$i++;
		}
		AriRenamer_writeScrollField($valueList,0);
	}
	AriRenamer_PageChange(0);
	select $AriRenamer_getList_processing;
}
global proc AriRenamer_GetNode(int $mode){
	global string $AriRenamer_getList_all[];         
	global string $AriRenamer_getList_processing[];  
	global string $AriRenamer_nameList_rename[];     
	global string $AriRename_History[50];
	global string $AriRename_ReHistory[50];
	global string $AriRenamer_UI_targetNameTextField;
	global string $AriRenamer_UI_pageTotal_IF;
	global string $AriRenamer_UI_viewTotalIF; 
	global string $AriRenameInputField[5];
	global string $AriRename_UI_resultCB;
	global string $AriRename_UI_ShapeCB;
	global string $AriRenamerButton[10];
	global string $AriRename_modeValue;
	string $leftList[];
	string $rightList[];
	if($mode==1){ 
		$leftList  = AriRenamer_readLeftField();
		$rightList = AriRenamer_readScrollField();
	}
	int $renameMode = 0;
	$renameMode  = `intField -q -v $AriRename_modeValue`;
	string $text = `textField -q -text $AriRenameInputField[2]`;
	string $selectList[];
	if($renameMode==0 || $renameMode==4) $selectList = `ls -sl`;
	if($renameMode==1 || $renameMode==2) $selectList = `ls -sl -type "file"`;
	string $selectShapeList[];
	if($renameMode==0)$selectShapeList = `ls -sl -s`;
	if($text != "" && size($selectList)==0){	
		$selectList = `ls`; 
	}
	if($text != ""){	
		string $searchList[];
		int $i=0;
		for($node in $selectList){
			string $baseNode=$node;
			string $sepa[];
			tokenize $node "|" $sepa;
			if(size($sepa)>=2){
				$baseNode=$sepa[size($sepa)-1];
			}
			if($text!="|"){ 
				if(`gmatch $baseNode ("*"+$text+"*")`){
					$searchList[$i]=$node;
					$i++;
				}
			}
			else{
				if(size($sepa)>=2){
					$searchList[$i]=$node;
					$i++;					
				}
			}
		}
		$selectList = $searchList;
		select -ne $selectList;	
		$selectShapeList = `ls -sl -s`;
	}
	if(!`checkBox -q -v $AriRename_UI_ShapeCB`){
		if(size($selectShapeList)>0){
			$selectList = stringArrayRemove($selectShapeList, $selectList);
		}
	}
	string $newLeftList[];
	string $newRightList[];
	if($mode==0){
		$newLeftList  = $selectList;
		$newRightList = $selectList;
	}
	if($mode==1){
		$selectList   = stringArrayRemove  ($leftList,  $selectList);
		$newLeftList  = stringArrayCatenate($leftList,  $selectList);
		$newRightList = stringArrayCatenate($rightList, $selectList);
	}
	$AriRenamer_getList_all = $newLeftList;
	$AriRenamer_getList_processing = $newLeftList;
	$AriRenamer_nameList_rename = $newRightList;
	select -ne $selectList;
	textField -e -text "" $AriRenameInputField[2];
	AriRenamer_NodeTypeReload("all");
	AriRenamer_TypeListPop();
}
global proc AriRenamer_ListExclude(){
	global string $AriRenamer_getList_all[];
	global string $AriRenamer_getList_processing[];  
	global string $AriRenamer_UI_targetNameTextField;
	global string $AriRenamer_UI_viewTotalIF;
	global string $AriRenamer_UI_pageNow_IF;
	global string $AriRename_History[50];
	string $selectObj[] = AriRenamer_getLeftSelectName();
	int $selectNum[]    = AriRenamer_getLeftSelectNumber();
	string $rightList[] = AriRenamer_readScrollField();
	string $baseList[];
	string $reRightList[];
	int $j=0;
	int $i=0;
	int $k=0;
	int $viewTotal = `intField     -q -v $AriRenamer_UI_viewTotalIF`;
	int $pageNow   = `intSliderGrp -q -v $AriRenamer_UI_pageNow_IF`;
	string $beforeList[] = $AriRenamer_getList_processing;
	for($i=0; $i<size($beforeList); $i++){
		int $numTrue=0;
		for($number in $selectNum){
			if($j == ($number-1) )$numTrue=1;
		}
		if(!$numTrue){
			$reRightList[$k] = $rightList[$i];
			$baseList[$k]    = $beforeList[$i];
			$k++;
		}
		$j++;
	}
	$AriRenamer_getList_all = $baseList;
	$AriRenamer_getList_processing = $baseList;
	AriRenamer_writeleftField(); 
	AriRenamer_writeScrollField($reRightList,0);
	AriRenamer_TypeListPop();
}
global proc AriRenamer_TexRenameUI_GO(int $mode){
	global string $AriRenamer_TexRenameCB[2];
	int $trueA = `checkBox -q -v $AriRenamer_TexRenameCB[0]`;
	int $trueB = `checkBox -q -v $AriRenamer_TexRenameCB[1]`;
	layoutDialog -dismiss ($mode+"_"+$trueA+"_"+$trueB);
}
global proc AriRenamer_TexRenameUI(){
	global string $AriRenamer_TexRenameCB[2];
    string $form = `setParent -q`;
    formLayout -e -width 300 $form;
	string $column1 = `columnLayout`;
		$AriRenamer_TexRenameCB[0] = `checkBox -l "コピーをリネーム (オリジナルの保持)" -v 1`;
		$AriRenamer_TexRenameCB[1] = `checkBox -l "file のパスも変更" -v 1`;
	setParent..;
	string $buttonOK     = `button -h 40 -label "Rename" -c "AriRenamer_TexRenameUI_GO(1)"`;
	string $buttonCancel = `button -h 40 -label "Cancel" -c "AriRenamer_TexRenameUI_GO(0)"`;
    formLayout -edit
	-af	$column1  "top"    0
	-af $column1  "left"   0
	-ac $buttonOK "top" 20 $column1
	-af $buttonOK "left"  0
	-ap $buttonOK "right" 0 50
	-ac $buttonCancel "top" 20 $column1
	-ac $buttonCancel "left"  0 $buttonOK
	-ap $buttonCancel "right" 0 100
	$form;
}
global proc AriRenamer_ResultWindow_PageChange(int $mode){
	global string $AriRenamer_UI_result_pane4Parent[4];
	global string $AriRenamer_UI_result_pane4Column[4];
	global string $AriRenamer_UI_result_pageNow_IF;
	global string $AriRenamer_UI_result_viewTotal_IF;
	global string $AriRenamer_UI_viewTotalIF;
	global string $AriRenamer_UI_pageTotal_IF;
	global string $AriRenamer_UI_result_pageTotal_IF;
	global string $AriRenamer_result_baseList[];
	global string $AriRenamer_result_inputList[];
	global string $AriRenamer_result_resultList[];
	global string $AriRenamer_result_newTexFullList[];
	global int $AriRenamer_result_errorPatternNumber[];
	global int $AriRenamer_result_renameMode;
	string $baseList[] = $AriRenamer_result_baseList;
	string $inputTexList[] =  $AriRenamer_result_inputList;
	string $resultNameList[] = $AriRenamer_result_resultList;
	string $newTexFullList[] = $AriRenamer_result_newTexFullList;
	int $errorPatternNumber[] = $AriRenamer_result_errorPatternNumber;
	int $renameMode = $AriRenamer_result_renameMode;
	string $labelList[];
	string $errorPatternString[];
	int $viewTotal = `intField -q -v $AriRenamer_UI_result_viewTotal_IF`; 
	int $nowPage   = `intSliderGrp -q -v $AriRenamer_UI_result_pageNow_IF`;
	int $pageTotal = (size($AriRenamer_result_baseList)/$viewTotal) +1;
	intField -e -v $pageTotal $AriRenamer_UI_result_pageTotal_IF;
	intSliderGrp -e -max $pageTotal $AriRenamer_UI_result_pageNow_IF;
	if($mode==1){
		$nowPage++;
	}
	if($mode==2){
		$nowPage--;
	}
	if($mode==4){
		$nowPage = 1;
	}
	if($mode==3){
		$nowPage = $pageTotal;
	}	
	if($nowPage > $pageTotal)$nowPage = $pageTotal;
	if($nowPage < 1)  $nowPage   = 1;
	intSliderGrp -e -v $nowPage $AriRenamer_UI_result_pageNow_IF;
	int $startNum = ($nowPage-1) * $viewTotal;
	int $endNum   = $startNum + $viewTotal-1;
	vector $color[];
	$color[0] = <<0.0, 0.0, 0.0>>;
	$color[1] = <<0.6, 0.8, 1.0>>;
	$color[2] = <<1.0, 1.0, 0.2>>;
	$color[3] = <<1.0, 0.4, 0.4>>;
	vector $errorColor[];
	int $jpTrue = false;
	if(`about -uil`=="ja_JP")$jpTrue = true;
	if(`optionVar -exists "AriRenamer_JP"`) $jpTrue = `optionVar -q "AriRenamer_JP"`;
	if($renameMode==0){
		$labelList[0] = "BaseName";
		$labelList[1] = "InputName";
		$labelList[2] = "Result";
		$labelList[3] = "";
		$errorPatternString[0]  = "";
		$errorPatternString[1]  = "Same name exists.";
		$errorPatternString[2]  = "The system automatically renamed.";
		$errorPatternString[12] = "No change of the same name.";
		$errorPatternString[13] = "No change due to space.";
		$errorPatternString[14] = "No change because the new name has no valid characters.";
		$errorPatternString[15] = "No change as it is the default node.";
		$errorPatternString[16] = "No changes for reference.";
		$errorPatternString[17] = "No change as it is a locked node.";
		$errorPatternString[10] = "Excluded because it does not exist.";
		if($jpTrue){
			$labelList[0] = "ベース名";
			$labelList[1] = "入力名";
			$labelList[2] = "結果";
			$labelList[3] = "";
			$errorPatternString[0]  = "";
			$errorPatternString[1]  = "別階層に同名存在(リネーム時の瞬間)";
			$errorPatternString[2]  = "システムが自動的にリネーム";
			$errorPatternString[12] = "同じ為変更なし";
			$errorPatternString[13] = "空白の為変更なし";
			$errorPatternString[14] = "新しい名前には正当な文字がない為変更なし";
			$errorPatternString[15] = "デフォルトノードの為変更なし";
			$errorPatternString[16] = "リファレンスの為変更なし";
			$errorPatternString[17] = "ロックされたノードの為変更なし";
			$errorPatternString[10] = "存在しないので除外";	
		}
		$errorColor[0] = $color[1];
		$errorColor[1] = $color[2];
		$errorColor[2] = $color[2];
		$errorColor[12] = $color[0];
		$errorColor[13] = $color[3];
		$errorColor[14] = $color[3];
		$errorColor[15] = $color[3];
		$errorColor[16] = $color[3];
		$errorColor[17] = $color[3];
		$errorColor[10] = $color[3];
	}
	if($renameMode==1){
		$labelList[0] = "file";
		$labelList[1] = "BasePath";
		$labelList[2] = "InputPath";
		$labelList[3] = "Result";
		$labelList[4] = "";
		$errorPatternString[0] = "";
		$errorPatternString[1] = "別階層に同名存在(リネーム時の瞬間)";
		$errorPatternString[2] = "システムが自動的にリネーム";
		$errorPatternString[11] = "ロックされている為変更不可";
		$errorPatternString[12] = "同パスの為変更なし";
		$errorPatternString[13] = "空白の為変更なし";
		$errorPatternString[14] = "有効名ではない為変更なし";
		$errorPatternString[15] = "デフォルトノードの為変更なし";
		$errorPatternString[16] = "リファレンスの為変更なし";
		$errorPatternString[17] = "ロックされたノードの為変更なし";
		$errorPatternString[10] = "存在しないので除外";
		$errorPatternString[20] = "リンクなしの為変更なし";
		$errorPatternString[21] = "リンクなし強制変更";
		$errorPatternString[30] = "キャンセル";
		if($jpTrue){
			$labelList[0] = "file";
			$labelList[1] = "元パス";
			$labelList[2] = "入力パス";
			$labelList[3] = "";
			$labelList[4] = "";
		}
		$errorColor[0] = $color[1];
		$errorColor[1] = $color[2];
		$errorColor[2] = $color[2];
		$errorColor[11] = $color[3];
		$errorColor[12] = $color[0];
		$errorColor[13] = $color[3];
		$errorColor[14] = $color[3];
		$errorColor[15] = $color[3];
		$errorColor[16] = $color[3];
		$errorColor[17] = $color[3];
		$errorColor[10] = $color[3];
		$errorColor[20] = $color[2];
		$errorColor[21] = $color[2];
		$errorColor[30] = $color[2];
	}
	if($renameMode==2){
		$errorPatternString[0]="";
		$errorPatternString[10]="fileノード存在なし";
		$errorPatternString[11]="テクスチャ存在なし(リンク切れ)";
		$errorPatternString[12]="変更なし";
		$errorPatternString[20]="すでに存在";
		$errorPatternString[21]="すでに存在リネームなしパスのみ変更";
		$errorPatternString[30]="失敗";
		$errorPatternString[40]="fileロックでリンク変更不可のためリネームもなし";
		$errorColor[0] = $color[1];
		$errorColor[10] = $color[3];
		$errorColor[11] = $color[3];
		$errorColor[12] = $color[2];
		$errorColor[20] = $color[2];
		$errorColor[21] = $color[2];
		$errorColor[30] = $color[3];
		$errorColor[40] = $color[3];
	}
	int $bgcList[];
	deleteUI $AriRenamer_UI_result_pane4Column[0];
	deleteUI $AriRenamer_UI_result_pane4Column[1];
	deleteUI $AriRenamer_UI_result_pane4Column[2];
	deleteUI $AriRenamer_UI_result_pane4Column[3];
	$AriRenamer_UI_result_pane4Column[0] = `columnLayout -w 30 -adj true -p $AriRenamer_UI_result_pane4Parent[0]`;
	$AriRenamer_UI_result_pane4Column[1] = `columnLayout -w 30 -adj true -p $AriRenamer_UI_result_pane4Parent[1]`;
	$AriRenamer_UI_result_pane4Column[2] = `columnLayout -w 30 -adj true -p $AriRenamer_UI_result_pane4Parent[2]`;
	$AriRenamer_UI_result_pane4Column[3] = `columnLayout -w 30 -adj true -p $AriRenamer_UI_result_pane4Parent[3]`;
	for($i=$startNum; $i<=$endNum; $i++){
		vector $striped_bgc = <<0.2, 0.2, 0.2>>;
		if($i%2 != 0){
			$striped_bgc = <<0.25, 0.25, 0.25>>;
		}
		if($i >= size($baseList))continue;
		string $sepa[];
		tokenize $baseList[$i] "|" $sepa;
		rowLayout -nc 2 -adj 2 -p $AriRenamer_UI_result_pane4Column[0] -h 28 -bgc ($striped_bgc.x) ($striped_bgc.y) ($striped_bgc.z);
		text -h 10 -w 30 -l ($i+1);
		textField -w 60 -h 20 -ed 0 -en 1 -text $sepa[size($sepa)-1];
		setParent..;
		rowLayout -nc 1 -adj 1 -p $AriRenamer_UI_result_pane4Column[1] -h 28 -bgc ($striped_bgc.x) ($striped_bgc.y) ($striped_bgc.z);
		textField -w 60 -h 20 -ed 0 -en 1 -text $inputTexList[$i];
		setParent..;
		rowLayout -p $AriRenamer_UI_result_pane4Column[2]  -nc 2 -adj 1 -h 28 -bgc ($striped_bgc.x) ($striped_bgc.y) ($striped_bgc.z);
		$texF3=`textField  -w 60 -ed 0 -en 1 -text $resultNameList[$i]`;
		if($renameMode == 2){
			button -h 20 -l "Open" -c ("AriRenamer_DireOpen(\""+$newTexFullList[$i]+"\")");
		}
		if($renameMode == 1){
			if(`filetest -f $resultNameList[$i]`){
				button -h 20 -l "Open" -c ("AriRenamer_DireOpen(\""+$resultNameList[$i]+"\")");
			}
			else{
				button -en false -h 20 -l "Open" -c ("");
			}
		}
		if($renameMode == 0){
			button -w 40 -h 20 -l "Sel" -c ("select "+$resultNameList[$i]);
		}
		setParent..;
		int $error = $errorPatternNumber[$i];
		rowLayout -p $AriRenamer_UI_result_pane4Column[3]  -nc 2 -adj 1 -h 28 -bgc ($striped_bgc.x) ($striped_bgc.y) ($striped_bgc.z);
		string $texF4 = `textField -w 60 -h 20 -ed 0 -en 1 -text ($errorPatternString[$error])`;
		setParent..;
		vector $bgc = $errorColor[$error];
		textField -e -bgc ($bgc.x) ($bgc.y) ($bgc.z) $texF3;
	}
	optionVar -iv "AriRenamerResultViewTotal" $viewTotal;
}
global proc AriRenamer_OpenResultWindow(){
	global string $AriRenamer_UI_pageTotal_IF;
	global string $AriRenamer_UI_viewTotalIF;
	global string $AriRenamer_UI_result_pageNow_IF;
	global string $AriRenamer_UI_result_pageTotal_IF;
	global string $AriRenamer_UI_result_column;
	global string $AriRenamer_UI_result_viewTotal_IF;
	global string $AriRenamer_UI_result_pane4Parent[4];
	global string $AriRenamer_UI_result_pane4Column[4];
	global int $AriRenamer_result_renameMode;
	int $viewTotal = 50;
	$viewTotal = `intField -q -v $AriRenamer_UI_viewTotalIF`;
	int $pageTotal = `intField -q -v $AriRenamer_UI_pageTotal_IF`;
	int $errorPatternNumber[];
	int $renameMode = $AriRenamer_result_renameMode;
	int $jpTrue = false;
	if(`about -uil`=="ja_JP")$jpTrue = true;
	if(`optionVar -exists "AriRenamer_JP"`) $jpTrue = `optionVar -q "AriRenamer_JP"`;
	string $labelList[];
	if($renameMode==0){
		$labelList[0] = "BaseName";
		$labelList[1] = "InputName";
		$labelList[2] = "Result";
		$labelList[3] = "";
		if($jpTrue){
			$labelList[0] = "ベース名";
			$labelList[1] = "入力名";
			$labelList[2] = "結果";
			$labelList[3] = "";
		}
	}
	if($renameMode==1){
		$labelList[0] = "file";
		$labelList[1] = "BasePath";
		$labelList[2] = "InputPath";
		$labelList[3] = "Result";
		$labelList[4] = "";
		if($jpTrue){
			$labelList[0] = "file";
			$labelList[1] = "元パス";
			$labelList[2] = "入力パス";
			$labelList[3] = "";
			$labelList[4] = "";
		}
	}
	if($renameMode==2){
	}
	if((`window -ex  AriRenamerResult`)==true)deleteUI AriRenamerResult;
	window -title "AriRenamerResult"  -w 200 -h 100 AriRenamerResult;
	string $formMain = `formLayout`;
	string $pageRow = `rowLayout -nc 10 -adj 5`;
		iconTextButton -i "timerew.png"   -c "AriRenamer_ResultWindow_PageChange(4)";
		iconTextButton -i "timeend.png"   -c "AriRenamer_ResultWindow_PageChange(2)";
		iconTextButton -i "timestart.png" -c "AriRenamer_ResultWindow_PageChange(1)";
		iconTextButton -i "timefwd.png"   -c "AriRenamer_ResultWindow_PageChange(3)";
		$AriRenamer_UI_result_pageNow_IF   = `intSliderGrp -w 300 -field true -cw 1 30 -v 1 -min 1 -max $pageTotal -dc "AriRenamer_ResultWindow_PageChange(0)" -cc "AriRenamer_ResultWindow_PageChange(0)"`;
		text -l "/";
		$AriRenamer_UI_result_pageTotal_IF = `intField -ed false -w 24 -v $pageTotal`;
		text -l "";
		text -l "1 PageTotal";
		$AriRenamer_UI_result_viewTotal_IF = `intField -w 38 -v $viewTotal -cc "AriRenamer_ResultWindow_PageChange(0)"`;
	setParent..;
	$AriRenamer_UI_result_column = `formLayout`;
	string $scroll  = `scrollLayout -cr true`;
	string $form    = `formLayout -w 100`;
	string $paneLay = `paneLayout -ps 1 25 100 -ps 2 25 100 -ps 3 25 100  -configuration "vertical4"`;
	if($renameMode == 1) paneLayout -e -ps 1 10 100 -ps 2 30 100 -ps 3 30 100 $paneLay;
	$AriRenamer_UI_result_pane4Parent[0] = `columnLayout -adj true`; setParent..;
	$AriRenamer_UI_result_pane4Parent[1] = `columnLayout -adj true`; setParent..;
	$AriRenamer_UI_result_pane4Parent[2] = `columnLayout -adj true`; setParent..;
	$AriRenamer_UI_result_pane4Parent[3] = `columnLayout -adj true`; setParent..;
	setParent..;
	text -p $AriRenamer_UI_result_pane4Parent[0] -l $labelList[0];
	text -p $AriRenamer_UI_result_pane4Parent[1] -l $labelList[1];
	text -p $AriRenamer_UI_result_pane4Parent[2] -l $labelList[2];
	text -p $AriRenamer_UI_result_pane4Parent[3] -l $labelList[3];
	$AriRenamer_UI_result_pane4Column[0] = `columnLayout -p $AriRenamer_UI_result_pane4Parent[0] -adj true`;
	$AriRenamer_UI_result_pane4Column[1] = `columnLayout -p $AriRenamer_UI_result_pane4Parent[1] -adj true`;
	$AriRenamer_UI_result_pane4Column[2] = `columnLayout -p $AriRenamer_UI_result_pane4Parent[2] -adj true`;
	$AriRenamer_UI_result_pane4Column[3] = `columnLayout -p $AriRenamer_UI_result_pane4Parent[3] -adj true`;
	formLayout -edit
		-af $paneLay "top"   0
		-af $paneLay "left"   0
		-af $paneLay "right" 0
		-af $paneLay "bottom" 0
	$form;
	setParent..;
	formLayout -e
		-af $scroll "top" 0
		-af $scroll "left" 0
		-af $scroll "right" 0
		-af $scroll "bottom" 0
	$AriRenamer_UI_result_column;
	formLayout -e
		-af $pageRow "top" 0
		-af $pageRow "left" 0
		-af $pageRow "right" 0
		-af $AriRenamer_UI_result_column "left" 0
		-af $AriRenamer_UI_result_column "right" 0
		-af $AriRenamer_UI_result_column "bottom" 0
		-ac $AriRenamer_UI_result_column "top" 0 $pageRow
	$formMain;
	showWindow;
	AriRenamer_ResultWindow_PageChange(0);
}
global proc AriRenamer_RenameGO_DataFile(){
	global string $AriRenamer_UI_baseNameTreeView;
	string $baseList[] = `treeView -q -ch "" $AriRenamer_UI_baseNameTreeView`;
	string $renameList[] = AriRenamer_readScrollField();
	string $renamePath[];
	for($i=0; $i < size($renameList); $i++){
		string $sepa[];
		tokenize $baseList[$i] "\\" $sepa;
		string $fileName = $sepa[size($sepa)-1];
		string $direName = `startString $baseList[$i] (size($baseList[$i])-size($fileName))`;
		$renamePath[$i] = $direName + $renameList[$i];
	}
	for($i=0; $i<size($baseList); $i++){
		string $renameName = $renamePath[$i];
		if($baseList[$i] == $renameName){	
			$errorPattern[$i]=12;
			continue;
		}
		if(`filetest -f $renameName`){
			continue;
		}
		int $renameResultTrue = 1;
		$renameResultTrue = `sysFile -ren $renameName $baseList[$i]`;
	}
}
global proc AriRenamer_RenameGO(){
	global string $AriRenamer_getList_processing[];  
	global string $AriRename_UI_resultCB;
	global string $AriRename_modeValue;
	global string $AriRenamer_TexRenameCB[2];
	int $renameMode =`intField -q -v $AriRename_modeValue`;
	if($renameMode == 3){
		AriRenamer_RenameGO_DataFile();
		return;
	}
	int $resultW = `checkBox -q -v $AriRename_UI_resultCB`;
	optionVar -iv "AriRenamerResultCheckBox" $resultW;
	if((`window -ex  AriRenamerResult`)==true)$resultW = true;
	string $cLayout[3];
	string $baseList[] = $AriRenamer_getList_processing;
	string $inputList[] = AriRenamer_readScrollField();
	string $existsList[];
	int $i=0;
	for($obj in $baseList){	
		if(objExists($obj)){
			$existsList[$i] = $obj;
			$i++;
		}
	}
	if(size($existsList)==0) return;
	select -ne $existsList;
	string $baseLongList[]   = `ls -sl -long`;
	string $referencedList[] = `ls -rn -sl`;
	int    $errorPatternNumber[];
	string $nameList01[];
	string $nameList02[];
	string $nameList03[];
	string $nameList04[];
	int    $bgcList[];
	int $amount = 0;
	int $maxText = size($baseLongList);
	progressWindow -title "Rename..." -progress $amount -status ("0 / "+ $maxText) -isInterruptable false;
	string $nullList[];
	if($renameMode==0){
		string $resultNameList[];
		int $groupDepth[];
		int $maxDepth;
		for($i=0;$i<size($baseLongList);$i++){
			string $sepa[];
			$groupDepth[$i]=`tokenize $baseLongList[$i] "|" $sepa`;
			$maxDepth=`max $maxDepth $groupDepth[$i]`;	
		}
		int $lapsTrue[];
		string $towLapsName[];
		for($laps=0; $laps<=1; $laps++){
			for($j=$maxDepth; $j>0; $j--){
				for($i=0;$i<size($baseLongList);$i++){
					if($groupDepth[$i]!=$j)continue;
					$baseLongName = $baseLongList[$i];
					if($laps==1){
						if($lapsTrue[$i]==false)continue;
						$baseLongName = $towLapsName[$i];
						string $sepa[];
						tokenize $baseLongList[$i] "|" $sepa;
						string $depthName = startString ($baseLongList[$i],(size($baseLongList[$i])-size($sepa[size($sepa)-1])));
						string $inputLongName = $depthName + $inputList[$i];
						if(objExists($inputLongName))continue;
					}
					$lapsTrue[$i] = false;
					if ( `progressWindow -query -isCancelled` ) break;
					progressWindow -edit -progress (int(($amount*1.0)/$maxText*100)) -status ($amount+" / "+$maxText);
					$amount++;
					string $resultName;
					string $sepa[];
					int $warning=0;
					$resultNameList[$i] = $existsList[$i];
					int $widthSize=160;
					$text_baseName[$i]   = $baseLongName;
					$text_resultName[$i] = $inputList[$i];
					$bgcList[$i] = 1;
					if(!objExists($baseLongName)){
						$errorPatternNumber[$i] = 10;
						$bgcList[$i] = 3;
						continue;
					}
					if($baseLongName == $inputList[$i]){
						$errorPatternNumber[$i] = 12;
						$bgcList[$i] = 0;
						continue;
					}
					if(endsWith ($baseLongName , ("|"+$inputList[$i]) )){
						$errorPatternNumber[$i] = 12;
						$bgcList[$i] = 0;
						continue;
					}
					if($inputList[$i]=="%" || $inputList[$i]==""){	
						$errorPatternNumber[$i] = 13;
						$bgcList[$i] = 0;
						continue;
					}
					/*
					if(0==isValidObjectName($inputList[$i])){
						$errorPattern[$i]=14;
						continue;
					}
					*/
					if(AriRenamer_unRenameNode($baseLongName)){
						$errorPatternNumber[$i] = 15;
						$bgcList[$i] = 2;
						continue;			
					}
					if(stringArrayContains($baseLongName,$referencedList)){
						$errorPatternNumber[$i] = 16;
						$bgcList[$i] = 2;
						continue;
					}
					int $lockTrue[]=`lockNode -q -l $baseLongName`;
					if($lockTrue[0]){
						$errorPatternNumber[$i] = 17;
						$bgcList[$i] = 1;
						continue;
					}
					if(catch($resultName = `rename $baseLongName $inputList[$i]`)){
						$errorPatternNumber[$i] = 14;
						$bgcList[$i] = 1;
						continue;
					}
					$resultNameList[$i] = $resultName;
					if($inputList[$i] == $resultName){
						$errorPatternNumber[$i] = 0;
						$bgcList[$i] = 1;
					}
					else{
						if(endsWith ($resultName , ("|"+$inputList[$i]) )){
							$errorPatternNumber[$i] = 1;
							$bgcList[$i] = 1;
						}
						else{
							$errorPatternNumber[$i] = 2;
							$bgcList[$i] = 2;
							$lapsTrue[$i] = true;
							$towLapsName[$i] = $resultName;
						}
					}
				}
			}
		}
		$nameList01 = $baseLongList;
		$nameList02 = $inputList;
		$nameList03 = $resultNameList;
		$nameList04 = $nullList;
	}
	progressWindow -endProgress;
	if($renameMode==1){
		for($i=0; $i<size($inputList); $i++){
			$inputList[$i] = substituteAllString($inputList[$i], "\\", "/");
		}
		int $linkMode=0;
		string $beforePathList[];
		for($i=0; $i<size($baseList); $i++){
			$bgcList[$i] = 1;
			if($linkMode==3){
				$errorPatternNumber[$i] = 30;
				$bgcList[$i] = 0;
				continue;
			}
			if(!objExists($baseList[$i])){
				$errorPatternNumber[$i]=10;
				$bgcList[$i] = 3;
				continue;
			}
			$beforePathList[$i] = `getAttr ($baseList[$i]+".fileTextureName")`;
			if($inputList[$i] == $beforePathList[$i]){
				$errorPatternNumber[$i] = 12;
				$bgcList[$i] = 0;
				continue;
			}
			if(`getAttr -l ($baseList[$i]+".fileTextureName")`){
				$errorPatternNumber[$i] = 11;
				$bgcList[$i] = 2;
				continue;
			}
			if(!`filetest -f ($inputList[$i])`){
				$bgcList[$i] = 2;
				string $dia;
				if($linkMode==0){
					$dia = `confirmDialog -m ($inputList[$i]+"\nは存在しません パスを変更しますか？") -button "はい" -button "以降はい" -button "いいえ" -button "以降いいえ" -button "キャンセル" -defaultButton "はい" -cancelButton "キャンセル"`;
					if($dia=="はい")$errorPatternNumber[$i]=21;
					if($dia=="以降はい")$linkMode=1;
					if($dia=="いいえ"){
						$errorPatternNumber[$i]=20;
						continue;
					}
					if($dia=="以降いいえ")$linkMode=2;
					if($dia=="キャンセル")$linkMode=3;
				}
				if($linkMode==1) $errorPatternNumber[$i]=21;
				if($linkMode==2){
					$bgcList[$i] = 0;
					$errorPatternNumber[$i]=20;
					continue;
				}
				if($linkMode==3){
					$bgcList[$i] = 0;
					$errorPatternNumber[$i]=30;
					continue;
				}
			}
			setAttr -type "string" ($baseList[$i]+".fileTextureName") $inputList[$i];
		}
		$nameList01 = $baseList;
		$nameList02 = $beforePathList;
		$nameList03 = $inputList;
		$nameList04 = $nullList;
		if($resultW){
		}
		/*
		if($resultW){
			if((`window -ex  AriRenamerResult`)==true)deleteUI AriRenamerResult;
			window -title "AriRenamerResult"  -w 200 -h 100 AriRenamerResult;
			scrollLayout;
			string $form =`formLayout -w 1400`;
			string $paneLay=`paneLayout -ps 1 15 100 -ps 2 15 100 -ps 3 20 100  -configuration "vertical4"`;
			if($renameMode == 1)paneLayout -e -ps 1 10 100 -ps 2 15 100 -ps 3 30 100 $paneLay;
			$cLayout[0]=`columnLayout -adj true`;
			if($renameMode == 0)text -l "ベース名";
			setParent..;
			$cLayout[1]=`columnLayout -adj true`;
			if($renameMode == 0)text -l "入力名";
			setParent..;
			$cLayout[2]=`columnLayout -adj true`;
			if($renameMode == 0)text -l "結果";
			setParent..;
			$cLayout[3]=`columnLayout -adj true`;
			if($renameMode == 0)text -l "";
			setParent..;
			formLayout -edit
			-af $paneLay "top"   0
			-af $paneLay "left"   0
			-af $paneLay "right" 0
			-af $paneLay "bottom" 0
			$form;
			for($i=0; $i<size($baseList); $i++){
				int $error=$errorPattern[$i];
				string $resultText=$renameList[$i];
				if($error==10 || $error==30){
					$resultText="";
				}
				if( $error==11 || $error==20 || $error==30){
					$resultText=$beforePathList[$i];
				}
				string $texF1 = `textField -p $cLayout[0] -w 60 -h 24 -ed 0 -en 1 -text $baseList[$i]`;
				string $texF2 = `textField -p $cLayout[1] -w 60 -h 24 -ed 0 -en 1 -text $beforePathList[$i]`;
				string $texF3;
				rowLayout -p $cLayout[2]  -nc 2 -adj 1 -h 24;
					$texF3=`textField  -w 60 -ed 0 -en 1 -text $resultText`;
					button -h 20 -l "Open" -c ("AriRenamer_DireOpen(\""+$resultText+"\")");
				setParent..;
				string $texF4=`textField -p $cLayout[3] -w 60 -h 24 -ed 0 -en 1 -text ($errorPatternString[$error])`;
				if($error==0 )textField -e -bgc 0.6 0.8 1 $texF3;
				if($error==11 || $error==20)textField -e -bgc 1 1 0 $texF3;
				if($error==10 || $error==21)textField -e -bgc 1 0.4 0.4 $texF3;
				if($error==30)textField -e -bgc 0.2 0.2 0.2 $texF3;
			}
			showWindow;
		}
		*/
	}
	if($renameMode==2){
		string $texDireList[];
		string $beforeTexFullList[];
		string $inputTexList[];
		string $newTexFullList[];
		string  $resultNameList[];
		int $copyTrue=1;
		int $linkTrue=1;
		string $dia="1_1_1";
		$dia=`layoutDialog -t "TextureRename" -ui "AriRenamer_TexRenameUI"`;
		string $sepaUI[];
		tokenize $dia "_" $sepaUI;
		if($sepaUI[1]=="0")$copyTrue=0;
		if($sepaUI[1]=="1")$copyTrue=1;
		if($sepaUI[2]=="0")$linkTrue=0;
		if($sepaUI[2]=="1")$linkTrue=1;
		if($sepaUI[0]!="1")return;
		/*
		$dia=`confirmDialog -m ("コピーをリネームしますか？") -button "コピーリネーム" -button "リネーム" -button "キャンセル" -defaultButton "コピーリネーム" -cancelButton "キャンセル"`;
		if($dia=="コピーリネーム")	$copyTrue=1;
		if($dia=="リネーム")		$copyTrue=0;
		if($dia=="キャンセル")		return;
		$dia=`confirmDialog -m ("fileパスも変更しますか？") -button "はい" -button "いいえ" -button "キャンセル" -defaultButton "はい" -cancelButton "キャンセル"`;
		if($dia=="はい")		$linkTrue=1;
		if($dia=="いいえ")		$linkTrue=0;
		if($dia=="キャンセル")	return;
		*/
		clear $beforeTexFullList;
		for($i=0; $i<size($baseList); $i++){
			$beforeTexFullList[$i]=`getAttr ($baseList[$i]+".fileTextureName")`;
		}
		string $untreatedFullList[]=$beforeTexFullList;
		for($i=0; $i<size($baseList); $i++){
			$untreatedFullList[$i]="-";
			int $renameTrue=1;
			string $sepa[];
			tokenize $beforeTexFullList[$i] "/" $sepa;
			$texDireList[$i]    = startString ($beforeTexFullList[$i],size($beforeTexFullList[$i])-size($sepa[size($sepa)-1]));
			$inputTexList[$i]  = $sepa[size($sepa)-1];
			$newTexFullList[$i] = $texDireList[$i] + $inputList[$i];
			string $beforeTex = $beforeTexFullList[$i];
			string $afterTex  = $newTexFullList[$i];
			$resultNameList[$i] = $inputList[$i];
			if(!objExists($baseList[$i])){
				$errorPatternNumber[$i]=10;
				continue;
			}
			if(!`filetest -f $beforeTex`){
				$errorPatternNumber[$i]=11;
				$resultNameList[$i]="";
				continue;
			}
			if($beforeTex==$afterTex){
				$errorPatternNumber[$i]=12;
				continue;
			}
			if(`filetest -f $afterTex`){
				if($linkTrue==0){
					$errorPatternNumber[$i]=20;
					continue;
				}
				if($linkTrue==1){
					$errorPatternNumber[$i]=21;
					$renameTrue=0;
				}
			}
			if($linkTrue==1){
				if(`getAttr -l ($baseList[$i]+".fileTextureName")`){
					$errorPatternNumber[$i]=40;
					continue;
				}
			}
			int $renameResultTrue=1;
			if($renameTrue){
				if($copyTrue==1 || stringArrayContains($beforeTex,$untreatedFullList)){
					$renameResultTrue=`sysFile -copy $afterTex $beforeTex`;	
				}
				else{
					$renameResultTrue=`sysFile -ren $afterTex $beforeTex`;	
				}
			}
			if($linkTrue==1){
				setAttr -type "string" ($baseList[$i]+".fileTextureName") $afterTex;
			}
			if(!$renameResultTrue){
				$errorPatternNumber[$i]=30;
			}
		}
		$nameList01 = $baseList;
		$nameList02 = $inputTexList;
		$nameList03 = $resultNameList;
		$nameList04 = $newTexFullList;
		if($resultW){
		}
	}
	if($renameMode==4){
		string $attrName = "preFilter";
		for($i=0; $i<size($baseList); $i++){
			string $obj = $baseList[$i];
			if(attributeExists($attrName,$obj)){
				setAttr -type "string" ($obj+"."+$attrName) $inputList[$i];
			}
		}
	}
	global string $AriRenamer_result_baseList[];
	global string $AriRenamer_result_inputList[];
	global string $AriRenamer_result_resultList[];
	global string $AriRenamer_result_newTexFullList[];
	global int $AriRenamer_result_errorPatternNumber[];
	global int $AriRenamer_result_renameMode;
	$AriRenamer_result_baseList       = $nameList01;
	$AriRenamer_result_inputList      = $nameList02;
	$AriRenamer_result_resultList     = $nameList03;
	$AriRenamer_result_newTexFullList = $nameList04;
	$AriRenamer_result_errorPatternNumber = $errorPatternNumber;
	$AriRenamer_result_renameMode         = $renameMode;
	if($resultW){
		AriRenamer_OpenResultWindow();
	}
	AriRenamer_GetNode(0);
	if((`window -ex AriMaterialList`)==true)AriMaterialList_RenamerReresult();
}
global proc AriRenamer_DireOpen(string $directory){
	$directory = substituteAllString($directory, "/", "\\");
	system ("explorer.exe /select,"+$directory);
}
global proc AriRenamer_Undo(){
	global string $AriRename_History[50];
	global string $AriRename_ReHistory[50];
	global string $AriRenamer_UI_targetNameTextField;
	int $localPos[2] = AriRenamer_CursorPos();
	string $nowTextList[] = AriRenamer_readScrollField();
	string $nowtext = AriRenamer_ToText($nowTextList,0);
	string $arrayText[];
	if($nowtext != $AriRename_History[0]){
		$arrayText = AriRenamer_textToArray($AriRename_History[0]);
		AriRenamer_writeScrollField($arrayText,2);
		AriRenamer_CursorPosMove($localPos[0],$localPos[1]);
		return;
	}
	if(size($AriRename_History)==1)return;
	$arrayText = AriRenamer_textToArray($AriRename_History[1]);
	AriRenamer_writeScrollField($arrayText,2);
	AriRenamer_CursorPosMove($localPos[0],$localPos[1]);
	for($i=size($AriRename_ReHistory);$i>0;$i--){
		if($i<50)	$AriRename_ReHistory[$i]=$AriRename_ReHistory[$i-1];
	}
	$AriRename_ReHistory[0]=$AriRename_History[0];
	for($i=0;$i<size($AriRename_History);$i++){
		if($i<50)	$AriRename_History[$i]=$AriRename_History[$i+1];
	}
	$AriRename_History[size($AriRename_History)-1]="";
	string $histry_work[]=$AriRename_History;
	clear $AriRename_History;
	for($i=0;$i<size($histry_work)-1;$i++){
		$AriRename_History[$i]=$histry_work[$i];
	}
}
global proc string AriRenamer_NumberString(int $num,int $digits){
	string $beforeNum=($num+"");
	string $afterNum;
	int $numPlus=$digits-size($beforeNum);
	$afterNum=$beforeNum;
	for($i=0;$i<$numPlus;$i++){
		$afterNum="0"+$afterNum;
	}
	return $afterNum;
}
global proc string AriRenamer_AlphabetString(int $num,int $mode){
	string $outString = "";
	string $alphabetA[] ={"","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"};
	string $alphabetB[] ={"","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"};
	int $decimal = 26;
	int $baseNum = $num-1;
	int $num26[];
	int $nowPaw = 1;
	int $nowPlus = 0;
	int $keta = 0;
	while($keta<10){
		$num26[$keta] = (( ($baseNum - $nowPlus ) / ($nowPaw)) % $decimal)+1;
		if($baseNum < $nowPlus)$num26[$keta] = 0;
		$nowPaw  = $nowPaw  * $decimal;
		$nowPlus = $nowPlus + $nowPaw;
		$keta++;
	}
	for($i=8; $i>=0; $i--){
		int $alpaNum = int($num26[$i]);
		if($mode==0) $outString = $outString + $alphabetA[$alpaNum];
		if($mode==1) $outString = $outString + $alphabetB[$alpaNum];
	}
	int $sum = 0;
	int $sumList[];
	for($i=1; $i<=5; $i++){
		$sum += pow(3,$i);
		$sumList[$i]=$sum;
	}
	return ($outString);
}
global proc AriRenamer_numbering_GO(int $mode){
	int $pos = 0;
	int $startNum = 1;
	int $digits = 3;
	int $alphabetMode = 0;
	int $individual = 1;
	int $delNumber  = 1;
	int $existence  = 1;
	if(`optionVar -exists "AriRenamerNumPos"`)			$pos          = `optionVar -q "AriRenamerNumPos"`;
	if(`optionVar -exists "AriRenamerNumStartNum"`)		$startNum     = `optionVar -q "AriRenamerNumStartNum"`;
	if(`optionVar -exists "AriRenamerNumFigure"`)		$digits       = `optionVar -q "AriRenamerNumFigure"`;
	if(`optionVar -exists "AriRenamerNumAlphabet"`)		$alphabetMode = `optionVar -q "AriRenamerNumAlphabet"`;
	if(`optionVar -exists "AriRenamerNumIndividual"`)	$individual   = `optionVar -q "AriRenamerNumIndividual"`;
	if(`optionVar -exists "AriRenamerNumDelNumber"`)	$delNumber    = `optionVar -q "AriRenamerNumDelNumber"`;
	if(`optionVar -exists "AriRenamerNumExistence"`)	$existence    = `optionVar -q "AriRenamerNumExistence"`;
	if($mode != 0){
		$digits = $mode;
	}
	if($mode == 100){
		$digits = 1;
		$alphabetMode = 1;
	}
	if($mode == 101){
		print "aaaa";
		$digits = 1;
		$alphabetMode = 2;
	}
	if($delNumber){ 
		AriRenamer_Condition_BackNumberDel();
	}
	int $localPos[2] = AriRenamer_CursorPos();
	string $renameTextList[] = AriRenamer_readScrollField();
	string $allList[];
	string $baseList[];
	string $exisList[];
	/*
	if($existence){
		$baseList = AriRenamer_readLeftField();
		string $nonUniqueList[];
		int $count = 0;
		for($i=0; $i<size($baseList); $i++){
			string $sepa[];
			tokenize $baseList[$i] "|" $sepa;
			if(size($sepa) != 1){
				$nonUniqueList[$count] = $baseList[$i];
				$count++;
			}
		}
		string $allList[]  = `ls -fl`;
		$count = 0;
		for($i=0; $i<size($allList); $i++){
			if(!stringArrayContains($allList[$i],$nonUniqueList)){
				string $sepa[];
				tokenize $allList[$i] "|" $sepa;
				$exisList[$count] = $sepa[size($sepa)-1];
				$count++;
			}
		}
	}
	*/
	int $nowNum = $startNum;
	string $reTextList[];
	int $i=0;
	int $y = $localPos[0]-1;
	int $x = $localPos[1];
	int $backPos = size($renameTextList[$y])-$x;
	string $processingList[];
	int $counter[];
	int $nameTotal = 0;
	for($text in $renameTextList){
		int $loop = 0;
		string $resultText="";
		while($loop < 100){
			int $decisionNum = $nowNum;
			$counter[size($processingList)] = $nowNum;
			int $processingTrue = false;
			if($individual){	
				for($j=0; $j<size($processingList); $j++){
					if($processingList[$j]==$text){
						$counter[$j] = $counter[$j]+1;
						$decisionNum = $counter[$j];
						$processingTrue = true;
						break;
					}
				}
			}
			else{
				$decisionNum=$i;
			}
			if($processingTrue == false){
				$processingList[size($processingList)] = $text;
			}
			string $number;
			if($alphabetMode==0) $number = AriRenamer_NumberString($decisionNum,$digits);
			if($alphabetMode==1) $number = AriRenamer_AlphabetString($decisionNum,0);
			if($alphabetMode==2) $number = AriRenamer_AlphabetString($decisionNum,1);
			if($alphabetMode==0 && $mode != 0)$number = AriRenamer_NumberString($decisionNum,$digits);
			if($pos==0){
				$resultText = $text + $number;
			}
			if($pos==1){
				$resultText = startString($text,$localPos[1])
									+$number
									+endString($text,size($text)-$localPos[1]);
			}
			if($pos==2){
				$resultText = startString($text,size($text)-$backPos)
									+$number
									+endString($text,$backPos);
			}
			if(!$existence)break;
			if(!`objExists $resultText`){
				break;
			}
			$loop++;
		}
		$reTextList[$i] = $resultText;
		$i++;
	}
	AriRenamer_writeScrollField($reTextList,1);
}
global proc AriRenamer_numbering_Save_GO(int $saveMode){
	global string $AriReNumber_field[3];
	global string $AriReNumber_radio[7];
	global string $AriReNumber_UI_individualCB; 
	global string $AriReNumber_UI_delNumberCB;  
	global string $AriReNumber_UI_existenceCB;  
	int $startNum   = `intField -q -v $AriReNumber_field[0]`;
	int $digits     = `intField -q -v $AriReNumber_field[1]`;
	int $individual = `checkBox -q -v $AriReNumber_UI_individualCB`; 
	int $delNumber  = `checkBox -q -v $AriReNumber_UI_delNumberCB`;  
	int $existence  = `checkBox -q -v $AriReNumber_UI_existenceCB`;  
	int $numberPos=0;
	if(`radioButton -q -select $AriReNumber_radio[0]`)$numberPos=0;
	if(`radioButton -q -select $AriReNumber_radio[1]`)$numberPos=1;
	if(`radioButton -q -select $AriReNumber_radio[2]`)$numberPos=2;
	int $alphabetMode=0;
	if(`radioButton -q -select $AriReNumber_radio[3]`)$alphabetMode=0;
	if(`radioButton -q -select $AriReNumber_radio[4]`)$alphabetMode=1;
	if(`radioButton -q -select $AriReNumber_radio[5]`)$alphabetMode=2;
	optionVar -iv "AriRenamerNumPos"        $numberPos;
	optionVar -iv "AriRenamerNumStartNum"   $startNum;
	optionVar -iv "AriRenamerNumFigure"     $digits;
	optionVar -iv "AriRenamerNumAlphabet"   $alphabetMode;
	optionVar -iv "AriRenamerNumIndividual" $individual;
	optionVar -iv "AriRenamerNumDelNumber"  $delNumber;
	optionVar -iv "AriRenamerNumExistence"  $existence;
	if($saveMode == 0) AriRenamer_numbering_GO(0);
	if($saveMode == 1) deleteUI AriRenamer_numbering;
	if($saveMode == 2) return;
	return;
}
global proc AriRenamer_Replace_GO(){
	global string $AriRenamer_UI_ReTextField[3];
	string $beforeString=`textField -q -text $AriRenamer_UI_ReTextField[0]`;
	string $afterString =`textField -q -text $AriRenamer_UI_ReTextField[1]`;
	if(size(strip($beforeString))==0)return;
	int $localPos[2] = AriRenamer_CursorPos();
	string $textList[] = AriRenamer_readScrollField();
	int $strSize=size($beforeString);
	string $reTextList[];
	int $i=0;
	for($text in $textList){
		int $k=0;
		$reTextList[$i]=$text;
		for($j=1;$j<size($reTextList[$i])-$strSize+2;$j++){
			string $sub=substring ($reTextList[$i],$j,$j-1+$strSize);
			if($sub==$beforeString){
				$reTextList[$i]=	startString($reTextList[$i],$j-1)
									+$afterString
									+endString($reTextList[$i],size($reTextList[$i])-($j-1+$strSize));
				$j=$j+(size($afterString)-1);
			}
			$k++;
			if($k>200)break;
		}
		$i++;
	}
	AriRenamer_writeScrollField($reTextList,1);
	AriRenamer_CursorPosMove($localPos[0],$localPos[1]);
}
global proc AriRenamer_Replace_Get(int $mode){
	global string $AriRenamer_UI_targetNameTextField;
	global string $AriRenamer_UI_ReTextField[3];
	string $selectString = `scrollField -q -selection $AriRenamer_UI_targetNameTextField`;
	textField -e -tx $selectString $AriRenamer_UI_ReTextField[$mode];
}
global proc AriRenamer_Replace_Menu(int $mode){
	global string $AriRenamer_UI_InsertMenu;
	global string $AriRenamer_UI_ReplaceMenu;
	global string $AriRenamer_UI_targetNameTextField;
	global string $AriRenamer_UI_ReTextField[3];
	if($mode==1){
		columnLayout -e -vis 0 $AriRenamer_UI_InsertMenu;
		columnLayout -e -vis 1 $AriRenamer_UI_ReplaceMenu;
		string $selectString = `scrollField -q -selection $AriRenamer_UI_targetNameTextField`;
		textField -e -tx $selectString $AriRenamer_UI_ReTextField[0];
	}
	if($mode==0){
		columnLayout -e -vis 1 $AriRenamer_UI_InsertMenu;
		columnLayout -e -vis 0 $AriRenamer_UI_ReplaceMenu;
	}
}
global proc AriRenamer_Replace_Window(){
	global string $AriRenamer_UI_targetNameTextField;
	global string $AriRenamer_UI_ReTextField[3];
	string $selectString = `scrollField -q -selection $AriRenamer_UI_targetNameTextField`;
	if((`window -ex  AriRenamer_replace`)==true)deleteUI AriRenamer_replace;
	window -title "置換"  -w 200 -h 100 -tlb  true AriRenamer_replace;
	columnLayout -adj true;
	rowLayout -nc 2 -adj 2;
		text -l "置換前:";
		$AriRenamer_UI_ReTextField[0]=`textField -w 100 -tx $selectString`;
	setParent..;
	rowLayout -nc 2 -adj 2;
		text -l "置換後:";
		$AriRenamer_UI_ReTextField[1]=`textField -w 100 `;
	setParent..;
	rowLayout -nc 2 -adj 1;
	text -w 50 -l "";
	button -w 100 -l "置換" -c"AriRenamer_Replace_GO";
	setParent..;
	setParent..;
	showWindow;
}
global proc AriRenamer_insertion(){
	global string $AriRenameInputField[5];
	global string $AriRename_radio[5];
	int $localPos[2] = AriRenamer_CursorPos();
	string $textList[] = AriRenamer_readScrollField();
	string $inputString=`textField -q -tx $AriRenameInputField[1]`;
	string $reTextList[];
	int $i=0;
	if(`radioButton -q -select $AriRename_radio[0]`){
		for($text in $textList){
			$reTextList[$i]=	startString($text,$localPos[1])
								+$inputString
								+endString($text,size($text)-$localPos[1]);
			$i++;
		}
	}
	if(`radioButton -q -select $AriRename_radio[1]`){
		int $y=$localPos[0]-1;
		int $x=$localPos[1];
		int $num = getGlobalNum($y);
		int $backPos = size($textList[$num])-$x;
		for($text in $textList){
			$reTextList[$i]=	startString($text,size($text)-$backPos)
								+$inputString
								+endString($text,$backPos);
			$i++;
		}
	}
	AriRenamer_writeScrollField($reTextList,1);
	AriRenamer_CursorPosMove($localPos[0],$localPos[1]+size($inputString));
}
global proc AriRenamer_allChange_window(){
	global string $AriRenamer_UI_targetNameTextField;
	global string $AriRenamer_UI_ReTextField[3];
	global string $AriRenameInputField[5];
	string $selectString = `scrollField -q -selection $AriRenamer_UI_targetNameTextField`;
	if((`window -ex  AriRenamer_allChange_window`)==true)deleteUI AriRenamer_allChange_window;
	window -title "全変換"  -w 200 -h 100 AriRenamer_allChange_window;
	columnLayout;
	frameLayout -cl 0 -cll 1 -l "直接入力" -w 210;
	columnLayout;
		rowLayout -nc 2;
			$AriRenameInputField[0]=`textField -w 200 -tx $selectString`;
		setParent..;
		rowLayout -nc 2;
			text -w 120 -l "";
			button -w 80 -l "全変換" -c"AriRenamer_allChange()";
		setParent..;
	setParent..;
	setParent..;
	showWindow;
}
global proc AriRenamer_allChange_windowGO(){
	global string $AriRenameInputField[5];
	string $inputString = `textField -q -tx $AriRenameInputField[0]`;
	if(size(strip($inputString))==0)return;
	string $textList[] = AriRenamer_readLeftField();
	string $reTextList[];
	int $i=0;
	for($text in $textList){
		$reTextList[$i] = $inputString;
		$i++;
	}
	AriRenamer_writeScrollField($reTextList,1);
	deleteUI AriRenamer_allChange_window;
}
global proc AriRenamer_allChange(){
	global string $AriRenameInputField[5];
	string $inputString = `textField -q -tx $AriRenameInputField[1]`;
	if(size(strip($inputString))==0)return;
	string $baseList[] = AriRenamer_readLeftField();
	string $reTextList[];
	int $i=0;
	for($text in $baseList){
		$reTextList[$i] = $inputString;
		$i++;
	}
	AriRenamer_writeScrollField($reTextList,1);
}
global proc AriRenamer_LeftSelect(int $mode){
	global string $AriRenamer_UI_targetNameTextField;
	global string $AriRenamer_UI_selectNumL;
	if($mode==1){
		string $selectList[] = AriRenamer_getLeftSelectName();
		select -cl;
		for($sel in $selectList){
			if( `objExists $sel` ){
				select -ne -add $sel;
			}
		}
	}
	int $num[] = AriRenamer_getLeftSelectNumber();
	if(size($num)==0)return;
	intField -e -v $num[size($num)-1] $AriRenamer_UI_selectNumL;
	$localLastNum = getLocalNum($num[size($num)-1]);
	AriRenamer_CursorPosMove($localLastNum, 0);
	setFocus $AriRenamer_UI_targetNameTextField;
}
global proc AriRenamer_RightSelect(){
	global string $AriRenamer_UI_baseNameTextField;
	global string $AriRenamer_UI_baseNameTreeView;
	int $localPos[] = AriRenamer_CursorPos();
	textScrollList -e -da $AriRenamer_UI_baseNameTextField;
	textScrollList -e -sii ($localPos[0]) $AriRenamer_UI_baseNameTextField;
	string $allList[] = `treeView -q -ch ""  $AriRenamer_UI_baseNameTreeView`;
	treeView -e -clearSelection $AriRenamer_UI_baseNameTreeView;
	treeView -e -selectItem $allList[($localPos[0])] true $AriRenamer_UI_baseNameTreeView;
	AriRenamer_LeftSelect(1);
}
global proc AriRenamer_ObjSelect(){
	global string $AriRenamer_UI_baseNameTextField;
	global string $AriRenamer_UI_baseNameTreeView;
	string $selectObj[] = `ls -sl`;
	textScrollList -e -da $AriRenamer_UI_baseNameTextField;
	treeView -e -clearSelection $AriRenamer_UI_baseNameTreeView;
	string $allList[] = `textScrollList -q -allItems $AriRenamer_UI_baseNameTextField`;
	for($obj in $selectObj){
		if( stringArrayContains($obj,$allList)){
			textScrollList -e -selectItem $obj $AriRenamer_UI_baseNameTextField;
			treeView -e -selectItem $obj true $AriRenamer_UI_baseNameTreeView;
		}
	}
}
global proc AriRenamer_DefName(){
	global string $AriRename_modeValue;
	int $renameMode =`intField -q -v $AriRename_modeValue`;
	string $selectObj[] = AriRenamer_getLeftSelectName();   
	int    $num[]       = AriRenamer_getLeftSelectNumber(); 
	string $rightList[] = AriRenamer_readScrollField();     
	int $i=0;
	for($obj in $selectObj){
		int $arrayNum = $num[$i]-1;
		if($renameMode==0){
			$rightList[$arrayNum] = $obj;
		}
		if($renameMode==1 || $renameMode==2){
			string $path = `getAttr ($obj+".fileTextureName")`;
			if($renameMode==1){
				$rightList[$arrayNum] = $path;
			}
			if($renameMode==2){
				string $sepa[];
				tokenize $path "/" $sepa;
				$rightList[$arrayNum] = $sepa[size($sepa)-1];
			}
		}
		$i++;
	}
	AriRenamer_writeScrollField($rightList,1);
	AriRenamer_LeftSelect(1);
}
global proc AriRenamer_DelBs(int $mode){
	int $localPos[2] = AriRenamer_CursorPos();
	int $amount = 0;
	string $textList[] = AriRenamer_readScrollField();
	int $maxText = size($textList);
	string $delList[];
	int $i=0;
	if($mode==0){
		for($text in $textList){
			$delList[$i] = startString($text,$localPos[1]);
			$delList[$i] = $delList[$i]+endString($text,size($text)-$localPos[1]-1);
			if(size($delList[$i])==0)$delList[$i]=$text;
			$i++;
		}
	}
	if($mode==1){
		int $y = $localPos[0]-1;
		int $x = $localPos[1];
		int $num = getGlobalNum($y);
		int $backPos = size($textList[$num])-$x;
		for($text in $textList){
			$delList[$i]=startString($text,size($text)-$backPos-1);
			$delList[$i]=$delList[$i]+endString($text,$backPos);
			if(size($delList[$i])==0)$delList[$i]=$text;
			$i++;
		}
		if($localPos[1]>1)$localPos[1]=$localPos[1]-1;
	}
	AriRenamer_writeScrollField($delList,1);
	AriRenamer_CursorPosMove($localPos[0],$localPos[1]);
}
global proc AriRenamer_GetDataFile(){
	global string $AriRenamer_UI_baseNameTreeView;
	treeView -e -ra $AriRenamer_UI_baseNameTreeView;
	treeView -e -nb 1 -arp false $AriRenamer_UI_baseNameTreeView;
	string $workspace = `workspace -q -rd`;
	string $fileList[] =`fileDialog2 -cap "select scenes" -dir $workspace -ds 1 -fm 4 -okc "シーン"`;
	string $fileNameList[];
	int $i=0;
	for($file in $fileList){
		string $icon = "out_list.png";
		string $extension_pic[]  = {".jpg",".png",".tga"};
		string $extension_psd[]  = {".psd"};
		string $extension_maya[] = {".ma",".mb"};
		for($ext in $extension_pic){
			if(endsWith($file, $ext)) $icon = "out_file.png";
		}
		for($ext in $extension_psd){
			if(endsWith($file, $ext)) $icon = "out_psdFileTex.png";
		}
		for($ext in $extension_maya){
			if(endsWith($file, $ext)) $icon = "commandButton.png";
		}
		string $sepa[];
		tokenize $file "\\" $sepa;
		string $labelText = $sepa[size($sepa)-1];
		$fileNameList[$i] = $labelText;
		treeView -e -addItem      $file ""          $AriRenamer_UI_baseNameTreeView; 
		treeView -e -displayLabel $file $labelText  $AriRenamer_UI_baseNameTreeView; 
		treeView -e -image        $file 1 $icon     $AriRenamer_UI_baseNameTreeView; 
		$i++;
	}
	AriRenamer_writeScrollField($fileNameList,0);
}
global proc AriRenamer_Condition_GO(int $mode){
	string $baseList[] = AriRenamer_readLeftField();
	if(size($baseList)==0)return;
	string $textList[] = AriRenamer_readScrollField();
	string $renameList[];
	int $i=0;
	for($obj in $textList){
		string $sepa[];
		tokenize $obj ":" $sepa;
		if(size($sepa)>=2)	$renameList[$i] = $sepa[size($sepa)-1];
		else $renameList[$i] = $textList[$i];
		$i++;
	}
	AriRenamer_writeScrollField($renameList,1);
}
global proc AriRenamer_Condition_FileName(int $mode){
	string $textList[] = AriRenamer_readLeftField();
	if(size($textList)==0)return;
	string $afterTextList[]=$textList;
	if($mode==0 || $mode==1){
		for($i=0;$i<size($textList);$i++){
			if(nodeType($textList[$i])=="file"){
				string $texture=`getAttr ($textList[$i]+".fileTextureName")`;
				if($texture=="") continue;
				if($mode==0)$afterTextList[$i] = basenameEx($texture);
				if($mode==1){
					$afterTextList[$i] = basename($texture,"");
					$afterTextList[$i] = substituteAllString ( $afterTextList[$i],".","_");
				}
			}
		}
	}
	if($mode==2){
		for($i=0;$i<size($textList);$i++){
			if(nodeType($textList[$i])=="transform"){
				string $parents[]=`listRelatives -p $textList[$i]`;
				if($parents[0]!=""){
					$afterTextList[$i]=$parents[0];
				}
			}
		}
	}
	AriRenamer_writeScrollField($afterTextList,1);
}
global proc AriRenamer_Condition_ShapeName(int $oldTrue){
	string $baseList[] = AriRenamer_readLeftField();
	if(size($baseList)==0)return;
	string $textList[] = AriRenamer_readScrollField();
	select $baseList;
	string $selectShapeList[]=`ls -sl -s`;
	select $selectShapeList;
	string $afterTextList[]=$textList;
	int $i=0;
	for($text in $baseList){
		if(stringArrayContains($text,$selectShapeList)){
			string $parent[]=`listRelatives -p $text`;
			if($oldTrue){
				print "Old";
				string $after[] = AriRenamer_NumberSeparate($parent[0],1);
				$afterTextList[$i] = ($after[0]+"Shape"+$after[1]);
			}
			else{
				string $after[] = AriRenamer_NumberSeparate($parent[0],0);
				string $afterString = "";
				if($after[1]!=""){	
					$afterString = int($after[1]);
				}
				$afterTextList[$i] = ($after[0]+"Shape"+ $afterString);
			}
		}
		$i++;
	}
	AriRenamer_writeScrollField($afterTextList,1);
}
global proc AriRenamer_Condition_BackNumberDel(){
	global string $AriRenameInputField[5];
	string $baseList[] = AriRenamer_readLeftField();
	if(size($baseList)==0)return;
	string $textList[] = AriRenamer_readScrollField();
	string $renameList[];
	int $i=0;
	for($obj in $textList){
		string $after[]=AriRenamer_NumberSeparate($obj,0);
		$renameList[$i]=$after[0];
		$i++;
	}
	AriRenamer_writeScrollField($renameList,1);
}
global proc AriRenamer_Condition_NumberDouble(int $digits){
	global string $AriRenameInputField[5];
	global string $AriRenamer_Condition_intField;
	string $baseList[] = AriRenamer_readLeftField();
	if(size($baseList)==0)return;
	string $textList[] = AriRenamer_readScrollField();
	string $renameList[];
	int $i=0;
	for($obj in $textList){
		string $after[]=AriRenamer_NumberSeparate($obj,0);
		$renameList[$i]=$after[0];
		int $num=0;
		if($after[1]!=""){
			$num=int($after[1]);
		}
		string $numString=($num+"");
		int $loopTotal=$digits-size($numString);
		for($j=0;$j<$loopTotal;$j++){
			$renameList[$i]=$renameList[$i]+"0";
		}
		$renameList[$i]=$renameList[$i]+$num;
		$i++;
	}
	AriRenamer_writeScrollField($renameList,1);
}
global proc AriRenamer_Condition_NumberDouble_intChange(int $value){
	global string $AriRenamer_Condition_intField;
	intField -e -v $value $AriRenamer_Condition_intField;
}
global proc AriRenamer_Condition_NumberDouble_Window(){
	global string $AriRenamer_Condition_intField;
	int $digits = 3;
	if(`optionVar -exists "AriRenamerDigits"`)$digits = `optionVar -q "AriRenamerDigits"`;
	if((`window -ex  AriRenamer_Condition_NumberDouble_Window`)==true)deleteUI AriRenamer_Condition_NumberDouble_Window;
	window -title "末尾数字桁数統一"  -w 100 -h 50 -tlb true AriRenamer_Condition_NumberDouble_Window;
	columnLayout;
	text -l "桁数";
	rowLayout -nc 2;
	$AriRenamer_Condition_intField = `intField  -v $digits -w 50`;
	iconTextButton -i "arrowDown.png";
		popupMenu -button 1 ;
		menuItem -l "1"  -c "AriRenamer_Condition_NumberDouble_intChange(1)";
		menuItem -l "2"  -c "AriRenamer_Condition_NumberDouble_intChange(2)";
		menuItem -l "3"  -c "AriRenamer_Condition_NumberDouble_intChange(3)";
		menuItem -l "4"  -c "AriRenamer_Condition_NumberDouble_intChange(4)";
		menuItem -l "5"  -c "AriRenamer_Condition_NumberDouble_intChange(5)";
		menuItem -l "6"  -c "AriRenamer_Condition_NumberDouble_intChange(6)";
		menuItem -l "7"  -c "AriRenamer_Condition_NumberDouble_intChange(7)";
		menuItem -l "8"  -c "AriRenamer_Condition_NumberDouble_intChange(8)";
		menuItem -l "9"  -c "AriRenamer_Condition_NumberDouble_intChange(9)";
		menuItem -l "10" -c "AriRenamer_Condition_NumberDouble_intChange(10)";
	setParent..;
	button -w 100 -l "OK" -c "AriRenamer_Condition_NumberDouble()";
	setParent..;
	showWindow;
}
global proc AriRenamer_Condition_GroupName(){
	string $baseList[] = AriRenamer_readLeftField();
	if(size($baseList)==0)return;
	string $reTextList[];
	int $i=0;
	for($base in $baseList){
		string $parents[] = `listRelatives -pa -p $base`;
		string $parent = $parents[0];
		if($parent != "")$reTextList[$i] = $parent;
		else $reTextList[$i] = $base;
		$i++;
	}
	AriRenamer_writeScrollField($reTextList,1);
}
global proc AriRenamer_getModeChange(){
	global string $AriRename_modeValue;
	global string $AriRenamer_OMenu[];
	global string $AriRenamerPaneLayout;
	global string $AriRenamer_UI_baseNameTextField;
	global string $AriRenamerButton[4];
	global string $AriRenamer_UI_baseNameTreeView;
	int $mode;
	$mode = `optionMenu -q -select $AriRenamer_OMenu[0]`;
	$mode --;
	int $paneSize = 50;
	int $paneSizeList[] = `paneLayout -q -paneSize $AriRenamerPaneLayout`;
	if($mode==1){
		$paneSize = 25;
	}
	paneLayout -e -paneSize 1 $paneSize 100  $AriRenamerPaneLayout;
	$baseList = AriRenamer_readLeftField();
	string $selectList[];
	int $i=0;
	for($obj in $baseList){	
		if(objExists($obj)){
			$selectList[$i] = $obj;
			$i++;
		}
	}
	select -ne $selectList;
	intField -e -v $mode $AriRename_modeValue;
	if($mode==3){
		intField -e -v 3 -vis true $AriRename_modeValue;
		textScrollList -e -vis true $AriRenamer_UI_baseNameTextField;
		treeView       -e -vis true  -bgc 0.8 0.8 0.8  $AriRenamer_UI_baseNameTreeView ;
		button -e -vis false $AriRenamerButton[1];
		button -e -vis true  $AriRenamerButton[2];
		button -e -vis true  $AriRenamerButton[3];
	}
	else{
		textScrollList -e -vis true $AriRenamer_UI_baseNameTextField;
		treeView       -e -vis true $AriRenamer_UI_baseNameTreeView;
		button -e -vis true  $AriRenamerButton[1];
		button -e -vis false $AriRenamerButton[2];
		button -e -vis false $AriRenamerButton[3];
	}
	if($mode==0) button -e -l "Rename" -bgc 1 1 0.2      $AriRenamerButton[0];
	if($mode==1) button -e -l "Link"   -bgc 1 0.6 0.3    $AriRenamerButton[0];
	if($mode==2) button -e -l "Rename" -bgc 1 0 0        $AriRenamerButton[0];
	if($mode==3) button -e -l "Rename" -bgc 1 1 1        $AriRenamerButton[0];
	if($mode==4) button -e -l "Rename" -bgc 0.2 0.2 0.2  $AriRenamerButton[0];
	AriRenamer_GetNode(0);
}
global proc AriRenamer_modeChangeGet(){
	global string $AriRename_modeValue;
	global string $AriRenamer_UI_baseNameTextField;
	global string $AriRenamer_UI_baseNameTreeView;
	global string $AriRenamer_UI_targetNameTextField;
	global string $AriRenamer_OMenu[3];
	global string $AriRenamerButton[10];
	$mode = `optionMenu -q -select $AriRenamer_OMenu[1]`;
	$mode --;
	if($mode==0){
		intField -e -v 0 $AriRename_modeValue;
		textScrollList -e -vis true  $AriRenamer_UI_baseNameTextField;
		treeView       -e -vis true $AriRenamer_UI_baseNameTreeView;
		button -e -vis true  $AriRenamerButton[1];
		button -e -vis false $AriRenamerButton[2];
		button -e -vis false $AriRenamerButton[3];
		AriRenamer_getModeChange();
	}
	if($mode==1){
		intField -e -v 3 -vis true $AriRename_modeValue;
		textScrollList -e -vis true $AriRenamer_UI_baseNameTextField;
		treeView       -e -vis true $AriRenamer_UI_baseNameTreeView;
		button -e -vis false $AriRenamerButton[1];
		button -e -vis true  $AriRenamerButton[2];
		button -e -vis true  $AriRenamerButton[3];
		button -e -l "Rename" -bgc 1 1 1     $AriRenamerButton[0];
	}
}
global proc AriRenamer_GetConditionWindow(){
	if((`window -ex  AriRenamer_GetConditionWindow`)==true)deleteUI AriRenamer_GetConditionWindow;
	window -title "条件取得"  -w 200 -h 100 AriRenamer_GetConditionWindow;
	scrollLayout;
	columnLayout;	
	rowLayout -nc 2;
	string $inputString=`textField -w 100 `;
	button -w 100 -l "タイプ" -c "";
	setParent..;
	button -w 200 -l "| を含む (同名オブジェクト)" -c "";
	button -w 200 -l ": を含む" -c "";
	button -w 200 -h 25 -label "階層取得" -ann "階層の選択を行ってから取得" -c "SelectHierarchy; AriRenamer_GetNode(0);";
	showWindow;
}
global proc AriRenamer_SetCondition_Window(){
	global string $AriRenamer_conditionUI[10];
	if((`window -ex  AriRenamer_SetCondition_Window`)==true)deleteUI AriRenamer_SetCondition_Window;
	window -title "条件リネーム"  -w 200 -h 100 AriRenamer_SetCondition_Window;
	scrollLayout -childResizable true;
	columnLayout -adj true;
	button -w 200 -l ": の前方消去" -c "AriRenamer_Condition_GO(1)" -ann " : が含まれていれば、 : の前方を消去します。";
	separator -w 200;
	button -w 200 -l "fileノードをテクスチャ名に"         -c "AriRenamer_Condition_FileName(0)" -ann "fileノードであればテクスチャ名に変更します。";
	button -w 200 -l "fileノードをテクスチャ名に拡張子付" -c "AriRenamer_Condition_FileName(1)" -ann "拡張子も付けます。( . は使用不可なので _ に)";
	separator -w 200;
	button -w 200 -l "末尾数字削除" -c "AriRenamer_Condition_BackNumberDel()"           -ann "末尾が数字だったらそれを消します。";
	button -w 200 -l "末尾数字桁数統一" -c "AriRenamer_Condition_NumberDouble_Window()" -ann "末尾が数字だったら桁数を統一します。";
	separator -w 200;
	button -w 200 -l "shapeノードを親+Shape名に" -c "AriRenamer_Condition_ShapeName(1)" -ann "親トランスフォーム名に従ってpCube001→pCube00Shape1の形にします。";
	button -w 200 -l "グループ名に" -c "AriRenamer_Condition_GroupName()";
	showWindow;
}
global proc AriRenamer_Numbering_Window(){
	global string $AriReNumber_field[3];
	global string $AriReNumber_radio[7];
	global string $AriReNumber_UI_individualCB; 
	global string $AriReNumber_UI_delNumberCB;  
	global string $AriReNumber_UI_existenceCB;  
	global int $AriReRenban;
	int $pos = 0;
	int $startNum = 1;
	int $digits = 3;
	int $alphabetMode = 0;
	int $individual = 1;
	int $delNumber = 1;
	int $existence = 1;
	if(`optionVar -exists "AriRenamerNumPos"`)			$pos      = `optionVar -q "AriRenamerNumPos"`;
	if(`optionVar -exists "AriRenamerNumStartNum"`)		$startNum = `optionVar -q "AriRenamerNumStartNum"`;
	if(`optionVar -exists "AriRenamerNumFigure"`)		$digits   = `optionVar -q "AriRenamerNumFigure"`;
	if(`optionVar -exists "AriRenamerNumAlphabet"`)		$alphabetMode = `optionVar -q "AriRenamerNumAlphabet"`;
	if(`optionVar -exists "AriRenamerNumIndividual"`)	$individual   = `optionVar -q "AriRenamerNumIndividual"`;
	if(`optionVar -exists "AriRenamerNumDelNumber"`)	$delNumber    = `optionVar -q "AriRenamerNumDelNumber"`; 
	if(`optionVar -exists "AriRenamerNumExistence"`)	$existence    = `optionVar -q "AriRenamerNumExistence"`;
	int $jpTrue = false;
	if(`about -uil`=="ja_JP")$jpTrue = true;
	if(`optionVar -exists "AriRenamer_JP"`) $jpTrue = `optionVar -q "AriRenamer_JP"`;
	string $label_Numbering = "Numberin Setting";
	string $label_StartNum  = "Start Number";
	string $label_Digit     = "Digit";
	string $label_End       = "End";
	string $label_CoStart   = "Cursor position (Start count)";
	string $label_CoEn      = "Cursor position (End count)";
	string $label_Same      = "The same name is the individual serial number";
	string $lable_End       = "Delete the End number";
	string $lable_Existing  = "Avoid existing names";
	if($jpTrue){
		$label_Numbering = "連番設定";
		$label_StartNum = "開始番号";
		$label_Digit    = "桁";
		$label_End      = "最後";
		$label_CoStart  = "カーソル位置 (前文字数カウント)";
		$label_CoEn     = "カーソル位置 (後文字数カウント)";
		$label_Same     = "同名個別連番";
		$lable_End      = "末尾数字削除";
		$lable_Existing = "存在名回避";
	}
	if((`window -ex AriRenamer_numbering`)==true)deleteUI AriRenamer_numbering;
	window -tlb true -title $label_Numbering  -w 200 -h 100 AriRenamer_numbering;
	string $form = `formLayout`;
	string $column = `columnLayout -adj true `;
	radioCollection;
	rowLayout -nc 3 ;
		$AriReNumber_radio[3]=`radioButton -label "012"`;
		$AriReNumber_radio[4]=`radioButton -label "abc"`;
		$AriReNumber_radio[5]=`radioButton -label "ABC"`;
	setParent..;
	rowLayout -nc 4;
		text -l ($label_StartNum+":");
		$AriReNumber_field[0]=`intField -w 50 -v $startNum`;
		text -l ("  "+$label_Digit+":");
		$AriReNumber_field[1]=`intField -w 20 -v $digits`;
	setParent..;
	separator ;
    radioCollection;
	$AriReNumber_radio[0]=`radioButton -label $label_End`;
	$AriReNumber_radio[1]=`radioButton -label $label_CoStart`;
	$AriReNumber_radio[2]=`radioButton -label $label_CoEn`;
	separator ;
	$AriReNumber_UI_individualCB = `checkBox -v $individual -l $label_Same`;
	$AriReNumber_UI_delNumberCB  = `checkBox -v $delNumber  -l $lable_End`;
	$AriReNumber_UI_existenceCB  = `checkBox -v $existence  -l $lable_Existing`;
	setParent..;
	string $saveButton[];
	string $form_savebutton = `formLayout`;
		$saveButton[0] = `button -l "Save"       -c "AriRenamer_numbering_Save_GO(2)"`;
		$saveButton[1] = `button -l "Save Close" -c "AriRenamer_numbering_Save_GO(1)"`;
		$saveButton[2] = `button -l "Apply"      -c "AriRenamer_numbering_Save_GO(0)"`;
	setParent..;
	formLayout -e
	-af $saveButton[2] "right"  0
	-af $saveButton[2] "top"    0
	-af $saveButton[2] "bottom" 0
	-ap $saveButton[2] "left"   0 50
	-af $saveButton[0] "left"   0
	-af $saveButton[0] "top"    0
	-ap $saveButton[0] "bottom" 0 50
	-ac $saveButton[0] "right"  0 $saveButton[2]
	-af $saveButton[1] "left"   0
	-ac $saveButton[1] "top"    0 $saveButton[0]
	-af $saveButton[1] "bottom" 0 
	-ac $saveButton[1] "right"  0 $saveButton[2]
	$form_savebutton;
	setParent..;
	formLayout -e
	-af $column "right"  0
	-af $column "top"    0
	-af $column "left"   0
	-af $form_savebutton "right"  0
	-af $form_savebutton "bottom" 0
	-af $form_savebutton "left"   0
	-ac $form_savebutton "top"    0 $column
	$form;
	if($pos==0)	radioButton -e -select $AriReNumber_radio[0];
	if($pos==1)	radioButton -e -select $AriReNumber_radio[1];
	if($pos==2)	radioButton -e -select $AriReNumber_radio[2];
	if($alphabetMode==0) radioButton -e -select $AriReNumber_radio[3];
	if($alphabetMode==1) radioButton -e -select $AriReNumber_radio[4];
	if($alphabetMode==2) radioButton -e -select $AriReNumber_radio[5];
	showWindow;
}
proc string local_getShapeType(string $node){
	string $child[] = `listRelatives -s $node`;
	string $type;
	if(size($child)!=0)	$type = `nodeType $child[0]`;
	else				$type = `nodeType $node`;
	return $type;
}
proc local_textListGet(){
	global string $AriRenamerUI_TypeTextSL;
	string $baseList[] = AriRenamer_readLeftField();
	string $typeList[];
	int $j=0;
	for($i=0; $i<size($baseList); $i++){
		$typeList[$i] = local_getShapeType($baseList[$i]);
	}
	ArrayTextScrollList($typeList,$AriRenamerUI_TypeTextSL);
}
global proc AriRenamer_Type(){
	global string $AriRenamerUI_TypeTextSL;
	if((`window -ex  AriRenamerTypeWindow`)==true)deleteUI AriRenamerTypeWindow;
		window -title "タイプ"  -w 200 -h 100 -tlb true  AriRenamerTypeWindow;
	string $form =`formLayout`;
	$AriRenamerUI_TypeTextSL =`textScrollList`;
	$buttonOK = `button -l "OK"`;
	setParent..;
	formLayout -edit
		-af $buttonOK "bottom" 0
		-af $buttonOK "left"   0
		-af $buttonOK "right"   0
		-af $AriRenamerUI_TypeTextSL "top"   0
		-af $AriRenamerUI_TypeTextSL "right" 0
		-af $AriRenamerUI_TypeTextSL "left" 0
		-ac $AriRenamerUI_TypeTextSL "bottom"   0 $buttonOK
	$form;
	showWindow;
	local_textListGet();
}
global proc AriRenamer_JP_EN(){
	confirmDialog -message "AriRenamerを再起動してください\n\nPlease restart AriRenamer";
	int $jpTrue;
	if(`about -uil`=="ja_JP")$jpTrue = true;
	if(`optionVar -exists "AriRenamer_JP"`) $jpTrue = `optionVar -q "AriRenamer_JP"`;
	optionVar -iv "AriRenamer_JP" (!$jpTrue);
}
global proc AriRenamer(){
	global string $AriRenamer_nameList_rename[];
	global int $AriRenamer_value_nowpage;
	global int $AriRenamer_value_viewTotal;
	global string $AriRenamer_UI_baseNameTextField;
	global string $AriRenamer_UI_baseNameTreeView;
	global string $AriRenamer_UI_targetNameTextField;
	global string $AriRenamer_UI_selectNumberText;
	global string $AriRenamer_UI_totalTF[4];
	global string $AriRenamer_UI_pageNow_IF;
	global string $AriRenamer_UI_pageTotal_IF;
	global string $AriRenamer_UI_viewTotalIF;
	global string $AriRenamer_UI_TypePop;
	global string $AriRenameInputField[5];
	global string $AriRename_radio[5];
	global string $AriRename_UI_resultCB;
	global string $AriRename_UI_ShapeCB;
	global string $AriRenamer_OMenu[3];
	global string $AriRenamerPaneLayout;
	global string $AriRenamerButton[10];
	global string $AriRename_modeValue;
	global string $AriRenamer_UI_selectNumL;
	global string $AriRenamer_UI_cursorPos[];
	int $jpTrue = false;
	if(`about -uil`=="ja_JP")$jpTrue = true;
	if(`optionVar -exists "AriRenamer_JP"`) $jpTrue = `optionVar -q "AriRenamer_JP"`;
	string $label_Hierarchy = "Hierarchy";
	string $label_Result    = "Result";   
	string $label_Insert    = "Insert";   
	string $label_Rewrite   = "Rewrite";
	string $label_CoStart   = "Start Count";
	string $label_CoEnd     = "End Count";
	string $lable_Replace   = "Replace";
	string $lable_ReplaceGO = "ReplaceGO";
	string $lable_Function  = "Function";
	string $lable_Before    = "Before";
	string $lable_After     = "After";
	string $lable_ReClose   = "Replace Close";
	if($jpTrue){
		$label_Hierarchy = "階層選択";
		$label_Result    = "結果";
		$label_Insert    = "挿入";
		$label_Rewrite   = "書換";
		$label_CoStart   = "前文字数一致";
		$label_CoEnd     = "後文字数一致";
		$lable_Replace   = "置換";
		$lable_ReplaceGO = "置換実行";
		$lable_Function  = "機能";
		$lable_Before    = "置換前";
		$lable_After     = "置換後";
		$lable_ReClose   = "置換終了";
	}
	$AriRenamer_value_nowpage = 1;
	if(`optionVar -exists "AriRenamerViewTotal"`)$AriRenamer_value_viewTotal = `optionVar -q "AriRenamerViewTotal"`;
	else $AriRenamer_value_viewTotal = 100;
	int $resultCheckBox=1;
	if(`optionVar -exists "AriRenamerResultCheckBox"`)$resultCheckBox = `optionVar -q "AriRenamerResultCheckBox"`;
	if((`window -ex  AriRenamer`)==true)deleteUI AriRenamer;
	window -title "AriRenamer"  -w 200 -h 100 AriRenamer;
	string $form =`formLayout`;
		string $pageView = `rowLayout -nc 15 -adj 1`;
		global string $AriRenamer_UI_pageChangeRow;
		$AriRenamer_UI_pageChangeRow = `rowLayout -nc 15 -adj 5 -bgc 0.5 0.5 0.5`;
		iconTextButton -c "AriRenamer_PageChange(4)" -i "timerew.png";
		iconTextButton -c "AriRenamer_PageChange(2)" -i "timeend.png";
		iconTextButton -c "AriRenamer_PageChange(1)" -i "timestart.png";
		iconTextButton -c "AriRenamer_PageChange(3)" -i "timefwd.png";
		$AriRenamer_UI_pageNow_IF = `intSliderGrp -v 1 -w 50 -min 1 -cw 1 30 -field true -dc "AriRenamer_PageChange(0)" -cc "AriRenamer_PageChange(0)"` ;
		text -l "/";
		$AriRenamer_UI_pageTotal_IF = `intField -ed false -w 24 -v 5`;
		setParent..;
		text  -l "";
		text  -l "1 PageTotal";
		$AriRenamer_UI_viewTotalIF  = `intField  -w 38 -v $AriRenamer_value_viewTotal -cc "AriRenamer_PageChange(0)"`;
		iconTextButton -h 20 -i "gear.png";
		popupMenu -button 1;
		menuItem -label "JP/EN" -c "AriRenamer_JP_EN()";
		setParent..;
		$AriRenamerPaneLayout = `paneLayout  -configuration "vertical2"`;
		string $rightForm = `formLayout`;
		$AriRenamer_UI_baseNameTextField  = `textScrollList -font "fixedWidthFont"  -ams 1 -sc "AriRenamer_LeftSelect(1)" -dcc "AriRenamer_DefName()"`;
		$AriRenamer_UI_baseNameTreeView   = `treeView     -enk true -nb 1 
												-itemDblClickCommand ""
												-scc "AriRenamer_LeftSelect(1)"  -vis false -adr false`;
		string $leftUnder = `rowLayout -nc 3 -vis false`;
		$AriRenamer_UI_selectNumL = `intField  -ed false -w 40`;
		$AriRenamer_UI_totalTF[0] = `textField -ed false -w 40`;
		setParent..;
		setParent..;
		formLayout -e
		-af $leftUnder "left" 0
		-af $leftUnder "right" 0
		-af $leftUnder "bottom" 0	
		-af $AriRenamer_UI_baseNameTextField "left" 0
		-af $AriRenamer_UI_baseNameTextField "right" 0
		-af $AriRenamer_UI_baseNameTextField "top" 0
		-ac $AriRenamer_UI_baseNameTextField "bottom" 0 $leftUnder
		$rightForm;
		string $ringFrome =`formLayout`;
		$AriRenamer_UI_targetNameTextField = `scrollField   `;
		popupMenu -button 3;
		menuItem -l "Select" -c "AriRenamer_RightSelect()";	
		setParent..;
		formLayout -e
		-af $AriRenamer_UI_targetNameTextField "left"  0
		-af $AriRenamer_UI_targetNameTextField "right" 0
		-af $AriRenamer_UI_targetNameTextField "top"   0
		-af $AriRenamer_UI_targetNameTextField "bottom" 0
		$ringFrome;
		setParent..;
		string $leftButtonG = `columnLayout -adj true`;
		$AriRenameInputField[2]   = `textField -w 60 -h 24 -cc "AriRenamer_GetNode(0)"`;
		rowLayout -nc 7 ;
			columnLayout -adj true;
				button  -w 60 -h 25 -label $label_Hierarchy -c "SelectHierarchy; AriRenamer_GetNode(0);";
				$AriRenamerButton[1]    = `button  -w 60 -h 50 -label "Get"      -ann "選択したノードを取得リスト一覧に追加" -bgc 0 0.8 0.5 -c "AriRenamer_GetNode(0)"`;
				$AriRenamerButton[2]    = `button  -w 60 -h 20 -label "File"      -ann ""  -vis false -bgc 0.9 0.9 0.9 -c "AriRenamer_GetDataFile()"`;
				$AriRenamerButton[3]    = `button  -w 60 -h 20 -label "Directory" -ann ""  -vis false -bgc 0.8 0.8 0.5 -c "AriRenamer_GetDataFile()"`;
			setParent..;
			columnLayout -adj true;
				string $pmButtonForm = `formLayout`;
				string $pButton = `button  -h 22 -l "+"   -c "AriRenamer_GetNode(1)"    -ann "取得リストに追加します"`;
				string $mButton = `button  -h 22 -l "-"   -c "AriRenamer_ListExclude()" -ann "取得リストから削除します"`;
				setParent..;
				formLayout -e
				-af $pButton "left" 0
				-ap $pButton "right" 0 50
				-af $mButton "right" 0
				-ac $mButton "left"  0 $pButton
				$pmButtonForm;
				$AriRename_UI_ShapeCB = `checkBox   -w 60 -h 25 -l "Shape" -v 0 -ann "shapeノードも読み込みます"`;
				button -w 60 -h 25 -l "Type"  -ann "";
				$AriRenamer_UI_TypePop = `popupMenu -button 1 `;
			setParent..;
		setParent..;
		setParent..;
		string $label_DelNum = "数字削除";
		string $label_UnifNum = "数字桁数統一";
		if($jpTrue == false){
			$label_DelNum  = "Delete numbers";
			$label_UnifNum = "Unified number of digits";
		}
		string $centerButtonG=`columnLayout -adj true -bgc 0.2 0.2 0.2`;
			string $formB;
			string $button[];
			string $rightRow =`rowLayout -nc 2 -adj 1`;
			string $deleteForm = `formLayout `;
				string $buttonDel = `button -w 30 -h 20 -label "[...] Del >" -ann "すべての行で カーソルより前にある文字数を保管し 後ろの文字を消去" -c "AriRenamer_DelBs(0)"`;
				string $buttonBs  = `button -w 30 -h 20 -label "< BS [...]"  -ann "すべての行で カーソルより後ろにある文字数を保管し 前の文字を消去"  -c "AriRenamer_DelBs(1)"`;
			setParent..;
				formLayout -e
				-af $buttonDel "left"  0             -ap $buttonDel "right" 0 50
				-ac $buttonBs  "left"  0 $buttonDel  -af $buttonBs  "right" 0
			$deleteForm;
			button -w 60 -h 24 -label "Undo" -c "AriRenamer_Undo()";
			setParent..;
			global string $AriRenamer_UI_InsertMenu;
			$AriRenamer_UI_InsertMenu = `columnLayout -adj true `;
			$formB = `formLayout`;
				$AriRenameInputField[1] = `textField `;
				$button[0]=`button -w 50 -h 20 -l $label_Insert  -ann "入力した文字をカーソルの位置に挿入" -c "AriRenamer_insertion()"`;
				$button[1]=`button -w 50 -h 20 -l $label_Rewrite -ann "入力した文字をカーソルの位置に挿入" -c "AriRenamer_allChange()"`;
			setParent..;
			formLayout -e
				-af $button[1] "right" 0
				-ac $button[0] "right" 0 $button[1]
				-af $AriRenameInputField[1] "left" 0
				-ac $AriRenameInputField[1] "right" 0 $button[0]
			$formB;
			$formB = `formLayout`;
			radioCollection;
				$AriRename_radio[0] = `radioButton -h 20 -label $label_CoStart -ann "前から数えたカーソルの位置に挿入\nCount from the front and insert at the cursor position"  -select`;
				$AriRename_radio[1] = `radioButton -h 20 -label $label_CoEnd   -ann "後ろから数えたカーソルの位置に挿入\nInsert at the cursor position counting from the back" `;
				string $numberButton = `button -w 50 -h 20 -l "012"`;
				popupMenu -button 1 ;
				menuItem -l "Apply" -c "AriRenamer_numbering_GO(0)" -ann "";
				menuItem -divider true;
				menuItem -l "1"     -c "AriRenamer_numbering_GO(1)" -ann "";
				menuItem -l "01"    -c "AriRenamer_numbering_GO(2)" -ann "";
				menuItem -l "001"   -c "AriRenamer_numbering_GO(3)" -ann "";
				menuItem -l "0001"  -c "AriRenamer_numbering_GO(4)" -ann "";
				menuItem -l "00001" -c "AriRenamer_numbering_GO(5)" -ann "";
				menuItem -l "a" -c "AriRenamer_numbering_GO(100)" -ann "";
				menuItem -l "A" -c "AriRenamer_numbering_GO(101)" -ann "";
				menuItem -divider true;
				menuItem -l $label_DelNum  -c "AriRenamer_Condition_BackNumberDel()";
				menuItem -l $label_UnifNum -subMenu true -c "AriRenamer_Condition_NumberDouble_Window()";
					menuItem -label "1" -c "AriRenamer_Condition_NumberDouble(1)";
					menuItem -label "2" -c "AriRenamer_Condition_NumberDouble(2)";
					menuItem -label "3" -c "AriRenamer_Condition_NumberDouble(3)";
					menuItem -label "4" -c "AriRenamer_Condition_NumberDouble(4)";
					menuItem -label "5" -c "AriRenamer_Condition_NumberDouble(5)";
					menuItem -label "6" -c "AriRenamer_Condition_NumberDouble(6)";
					menuItem -label "7" -c "AriRenamer_Condition_NumberDouble(7)";
				setParent -menu ..;
				menuItem -divider true;
				menuItem -i "gear.png" -l "Option"       -c "AriRenamer_Numbering_Window()";
				setParent..;
			formLayout -e
				-af $AriRename_radio[0] "left"  0
				-ac $AriRename_radio[1] "left"  0 $AriRename_radio[0]
				-af $numberButton "right" 0
			$formB;
			string $function_label[];
			string $function_command[];
			string $function_annotation[];
			$function_label[0] = "機能";
			$function_label[1] = ": の前方消去";
			$function_label[2] = "fileノードをテクスチャ名に";
			$function_label[3] = "fileノードをテクスチャ名に(拡張子付)";
			$function_label[4] = "数字削除";
			$function_label[5] = "数字桁数統一";
			$function_label[6] = "shapeノードを標準名に(親+Shape名) ～Maya2018";
			$function_label[7] = "親グループ名に";
			$function_label[8] = "shapeノードを標準名に(親+Shape名) Maya2019～";
			int $functionJPTrue = $jpTrue;
			if($functionJPTrue == false){
				$function_label[0] = "Function";
				$function_label[1] = "Remove the front of : ";
				$function_label[2] = "File node to texture name";
				$function_label[3] = "File node to texture name (extension)";
				$function_label[4] = "Delete numbers";
				$function_label[5] = "Unified number of digits";
				$function_label[6] = "Shape Node to \"Parent+Shape\" (-Maya2018)";
				$function_label[7] = "To parent group name";
				$function_label[8] = "Shape Node to \"Parent+Shape\" (Maya2019-)";
			}
			$function_command[0] = "";
			$function_command[1] = "AriRenamer_Condition_GO(1);";
			$function_command[2] = "AriRenamer_Condition_FileName(0);";
			$function_command[3] = "AriRenamer_Condition_FileName(1);";
			$function_command[4] = "AriRenamer_Condition_BackNumberDel();";
			$function_command[5] = "AriRenamer_Condition_NumberDouble_Window();";
			$function_command[6] = "AriRenamer_Condition_ShapeName(1);";
			$function_command[7] = "AriRenamer_Condition_GroupName();";
			$function_command[8] = "AriRenamer_Condition_ShapeName(0);";
			$function_annotation[0] = "";
			$function_annotation[1] = " : より前にある文字を消去します。\nErases the characters before A.";
			$function_annotation[2] = "fileノードであればテクスチャ名に変更します。";
			$function_annotation[3] = "拡張子も付けます。( . は使用不可なので _ に)";
			$function_annotation[4] = "末尾が数字の場合、数字を消します。";
			$function_annotation[5] = "末尾が数字の場合、桁数を統一します。";
			$function_annotation[6] = "親トランスフォーム名に従ってpCube001→pCube00Shape1の形にします。";
			$function_annotation[7] = "親グループ名の名前に統一します。";
			$function_annotation[8] = "";
			$formB=`formLayout`;
				$button[0] = `button -w 50 -label $lable_Replace -ann "置換メニューを表示" -c "AriRenamer_Replace_Menu(1)"`;
				$button[3] = `button -w 50 -label $lable_Function -ann "" `;
					popupMenu -button 1 ;
					menuItem -l $function_label[7] -c $function_command[7] -ann $function_annotation[7];
					menuItem -l $function_label[1] -c $function_command[1] -ann $function_annotation[1];
					menuItem -divider true;
					menuItem -l $function_label[2] -c $function_command[2] -ann $function_annotation[2];
					menuItem -l $function_label[3] -c $function_command[3] -ann $function_annotation[3];
					menuItem -divider true;
					menuItem -l $function_label[4] -c $function_command[4] -ann $function_annotation[4];
					menuItem -l $function_label[5] -c $function_command[5] -ann $function_annotation[5];
					menuItem -divider true;
					menuItem -l $function_label[6] -c $function_command[6] -ann $function_annotation[6];
					menuItem -l $function_label[8] -c $function_command[8] -ann $function_annotation[8];
			setParent..;
			formLayout -e
			-af $button[0] "left"  0             -ap $button[0] "right" 0 50
			-ac $button[3] "left"  0 $button[0]  -ap $button[3] "right" 0 100
			$formB;
			setParent..;
			global string $AriRenamer_UI_ReplaceMenu;
			$AriRenamer_UI_ReplaceMenu = `columnLayout -vis false -adj true -bgc 0.3 0.3 0.3 `;
			global string $AriRenamer_UI_ReTextField[3];
			rowLayout -nc 2 -adj 2;
			button -w 60 -h 20 -l $lable_Before -c "AriRenamer_Replace_Get(0)";
			$AriRenamer_UI_ReTextField[0] = `textField -w 100 `;
			setParent..;
			rowLayout -nc 2 -adj 2;
			button -w 60 -h 20 -l $lable_After -c "AriRenamer_Replace_Get(1)";
			$AriRenamer_UI_ReTextField[1] = `textField -w 100 `;
			setParent..;
			rowLayout -nc 2 -adj 2;
			button -w 100 -l $lable_ReClose -bgc 0 0 0 -c "AriRenamer_Replace_Menu(0)";
			button -w 100 -l $lable_ReplaceGO -bgc 0 0.5 1 -c "AriRenamer_Replace_GO()";
			setParent..;
			setParent..;
		setParent..;
		string $rightButtonG=`rowLayout -nc 2`;
		columnLayout;
		$AriRenamer_OMenu[0] = `optionMenu -w 60 -h 24 -label "" -changeCommand "AriRenamer_getModeChange()"`;
				menuItem -label "Node";
				menuItem -label "Path";
				menuItem -label "Texture";
			separator -h 3 -w 60 -st "in";
			rowLayout -nc 2;
			$AriRename_UI_resultCB = `checkBox -v $resultCheckBox -h 24 -l "" -ann "リネーム結果ウィンドウを表示します"`;
			button -w 40 -h 20 -l $label_Result -c "AriRenamer_OpenResultWindow()";
			setParent..;
			$AriRenamerButton[0] = `button -w 60 -h 50 -bgc 1 1 0.2 -label "Rename" -c "AriRenamer_RenameGO()" -ann "左フィールド名前のノードを右フィールドの名前にリネーム" `;
		setParent..;
		columnLayout;
				$AriRename_modeValue = `intField -vis false -v 0 -w 40 `;
			setParent..;
		setParent..;
		setParent..;
	setParent..;
	formLayout -edit
		-af $leftButtonG "bottom" 0
		-af $leftButtonG "left"   0
		-af $rightButtonG "bottom"  0
		-af $rightButtonG "right"   0
		-af $centerButtonG "bottom" 0
		-ac $centerButtonG "right"  0 $rightButtonG 
		-ac $centerButtonG "left"   0 $leftButtonG
		-ac $pageView "bottom" 0 $rightButtonG
		-af $pageView "left"   0
		-af $pageView "right"  0
		-af $AriRenamerPaneLayout "top"   0
		-af $AriRenamerPaneLayout "left"  0
		-af $AriRenamerPaneLayout "right" 0
		-ac $AriRenamerPaneLayout "bottom" 0 $pageView
		$form;
	showWindow;
	AriRenamer_GetNode(0);
	scriptJob -p "AriRenamer" -event "SelectionChanged" "AriRenamer_ObjSelect()";
}
