//
// ScriptName : AriScriptLauncher
// Contents   : ローカルスクリプトフォルダにあるAriスクリプトを一覧します。
// Author     : Ari
// URL        : http://cgjishu.net/
// Since      : 2018/01/06
// LastUpdate : 
// Note       : 
// Help       : http://cgjishu.net/blog-entry-263.html
//
//--------------------------------------------------------------------------




proc string getAriMelList(string $command){
	
	
	string $list[];
	
	
	string $URLList[]= {
		"http://cgjishu.net/blog-entry-3.html",   "AriMirror",
		"http://cgjishu.net/blog-entry-5.html",   "AriIconViewer",
		"http://cgjishu.net/blog-entry-6.html",   "AriSymmetryChecker",
		"http://cgjishu.net/blog-entry-7.html",   "AriCombineExtract",
		"http://cgjishu.net/blog-entry-9.html",   "AriReversedFaceSelector",
		"http://cgjishu.net/blog-entry-10.html",  "AriAllCloseWindow",
		"http://cgjishu.net/blog-entry-13.html",  "AriPolygonCounter",
		"http://cgjishu.net/blog-entry-16.html",  "AriSceneOpener",
		"http://cgjishu.net/blog-entry-19.html",  "AriVertexColorEditor",
		"http://cgjishu.net/blog-entry-37.html",  "AriSortOutliner",
		"http://cgjishu.net/blog-entry-41.html",  "AriShowHideChange",
		"http://cgjishu.net/blog-entry-42.html",  "AriRenamer",
		"http://cgjishu.net/blog-entry-44.html",  "AriStraightVertex",
		"http://cgjishu.net/blog-entry-46.html",  "AriHotkeyList",
		"http://cgjishu.net/blog-entry-51.html",  "AriUVRatio",
		"http://cgjishu.net/blog-entry-58.html",  "AriUVGridding",
		"http://cgjishu.net/blog-entry-63.html",  "AriTextureReload",
		"http://cgjishu.net/blog-entry-65.html",  "AriCompactToolSettings",
		"http://cgjishu.net/blog-entry-69.html",  "AriUVScaleChecker",
		"http://cgjishu.net/blog-entry-73.html",  "AriReFreezeTranslate",
		"http://cgjishu.net/blog-entry-74.html",  "AriUnparentOne",
		"http://cgjishu.net/blog-entry-77.html",  "AriDirectoryOpener",
		"http://cgjishu.net/blog-entry-79.html",  "AriReFreezeRotate",
		"http://cgjishu.net/blog-entry-81.html",  "AriReFreezeScale",
		"http://cgjishu.net/blog-entry-87.html",  "AriMergeBorderVertex",
		"http://cgjishu.net/blog-entry-88.html",  "AriSetPivot",
		"http://cgjishu.net/blog-entry-95.html",  "AriRoundOffPosition",
		"http://cgjishu.net/blog-entry-99.html",  "AriKeepUnusedNodes",
		"http://cgjishu.net/blog-entry-110.html", "AriBoundingBoxScaling",
		"http://cgjishu.net/blog-entry-115.html", "AriProjectSetter",
		"http://cgjishu.net/blog-entry-117.html", "AriSelectMaterialAndObject",
		"http://cgjishu.net/blog-entry-118.html", "AriSelectUVLoop",
		"http://cgjishu.net/blog-entry-127.html", "AriResetAnimationPosition",
		"http://cgjishu.net/blog-entry-134.html", "AriWindowPositionReset",
		"http://cgjishu.net/blog-entry-136.html", "AriCompactToolSettings",
		"http://cgjishu.net/blog-entry-140.html", "AriUVAdsorption",
		"http://cgjishu.net/blog-entry-150.html", "AriSelectHardEdgeInside",
		"http://cgjishu.net/blog-entry-152.html", "AriUVAdsorptionMove",
		"http://cgjishu.net/blog-entry-153.html", "AriStopwatch",
		"http://cgjishu.net/blog-entry-154.html", "AriUVDisplayImageChanger",
		"http://cgjishu.net/blog-entry-164.html", "AriAssetChanger",
		"http://cgjishu.net/blog-entry-171.html", "AriFaceMaterialChecker",
		"http://cgjishu.net/blog-entry-172.html", "AriSelectEdgeRing",
		"http://cgjishu.net/blog-entry-174.html", "AriResetAnimation",
		"http://cgjishu.net/blog-entry-176.html", "AriViewWindow",
		"http://cgjishu.net/blog-entry-184.html", "AriUVFit",
		"http://cgjishu.net/blog-entry-189.html", "AriLayerSwitch",
		"http://cgjishu.net/blog-entry-196.html", "AriTransferPosition",
		"http://cgjishu.net/blog-entry-201.html", "AriUVExtract",
		"http://cgjishu.net/blog-entry-204.html", "AriUVReversSelector",
		"http://cgjishu.net/blog-entry-206.html", "AriAniKeySmooth",
		"http://cgjishu.net/blog-entry-207.html", "AriAniSetPlaybackRange",
		"http://cgjishu.net/blog-entry-216.html", "AriCircleVertex",
		"http://cgjishu.net/blog-entry-225.html", "AriAnimationCopy",
		"http://cgjishu.net/blog-entry-229.html", "AriQuadrangulateRing",
		"http://cgjishu.net/blog-entry-234.html", "AriUVSetList",
		"http://cgjishu.net/blog-entry-244.html", "AriJointBendOrient",
		"http://cgjishu.net/blog-entry-245.html", "AriJointStraight",
		"http://cgjishu.net/blog-entry-248.html", "AriUVPixelScale",
		"http://cgjishu.net/blog-entry-251.html", "AriAniKeyScale",
		"http://cgjishu.net/blog-entry-252.html", "AriAniFractionSelect",
		"http://cgjishu.net/blog-entry-252.html", "AriAniFractionSideKey",
		"http://cgjishu.net/blog-entry-254.html", "AriDeleteEdgePreserveBorder",
		"http://cgjishu.net/blog-entry-258.html", "AriSplitPolygon",
		"http://cgjishu.net/blog-entry-263.html", "AriScriptLauncher"
		
	};
	
	string $url = "null";
	for($i=0; $i<size($URLList); $i++){
		if($URLList[$i] == $command){
			$url = $URLList[$i-1];
		}
	}
	return $url;
}
global proc AriScriptLauncher_AddShell(string $command, string $iconImage, int $optionTrue, string $url){
	string $shelfLayout = "ShelfLayout";
	string $active = `shelfTabLayout -q -selectTab $shelfLayout`;
	if(!`filetest -f $iconImage`){
		$iconImage = "commandButton.png";
	}
	string $shelfBut = `shelfButton 
		-rpt true 
		-i   $iconImage 
		-l   $command 
		-ann $command
		-c   $command
		-p   $active `;
	if($url != "null"){
		popupMenu -parent $shelfBut -button 3;
		menuItem  -l "Help Web" -stp "mel" -c ("launch -web \""+$url+"\"");
	}
	if($optionTrue){
		shelfButton -e -dcc ($command+"Options") $shelfBut;
	}
}
proc string[] AriScriptLauncher_GetMELList(){
	global string $AriScriptLauncher_UI_direTextF;
	string $melDire  = `textField -q -text $AriScriptLauncher_UI_direTextF`;
	string $list[] = `getFileList -fld $melDire  -fs "*.mel"`;
	string $shelfLayout="ShelfLayout";
	string $active = `shelfTabLayout -q -selectTab $shelfLayout`;
	string $melList[];
	int $i=0;
	for($mel in $list){
		if(startsWith($mel,"Ari")){
			string $sepa[];
			tokenize $mel "." $sepa;
			string $command = $sepa[0];
			$melList[$i] = $command;
			$i++;
		}
	}
	return $melList;
}
proc string AriScriptLauncher_IconExtension(string $command){
	global string $AriScriptLauncher_UI_iconTextF;
	string $iconDire  = `textField -q -text $AriScriptLauncher_UI_iconTextF`;
	string $icon;
	string $iconPath = $iconDire + $command + ".png";
	if(`filetest -f $iconPath`){
		$icon = $iconPath;
	}
	else{
		$icon = "commandButton.png";
	}
	return $icon;
}
proc string urlcheck(string $command){
	string $url;
	string $getPath = `whatIs $command`;
	int $subInt = 20;
	if(startsWith($getPath,"Mel"))   $subInt=24;
	if(startsWith($getPath,"Script"))$subInt=17;
	string $path = endString($getPath,size($getPath)-$subInt);
	if(!`filetest -f $path`)return "null";
	string $getText[] = freadAllLines($path);
	string $urlText ="";
	for($text in $getText){
		if(startsWith($text,"// Help")){
			$urlText = $text;
			break;
		}
	}
	string $sepa[];
	tokenize $urlText " " $sepa;
	$url = $sepa[3];
	if(!startsWith($url,"http:"))$url="null";
	return $url;
}
global proc AriScriptLauncher_urlOpen(string $command, int $checkTrue){
	if($checkTrue==false){
		launch -web $command;
	}
	else{
		string $url = urlcheck($command);
		if($url!="null")launch -web $url;
	}
}
global proc AriScriptLauncher_melList_Reload(){
	global string $AriScriptLauncher_UI_direSL;
	global string $AriScriptLauncher_UI_direCL;
	string $melList[]  = AriScriptLauncher_GetMELList();
	string $melListIconTrue[];
	string $melListIconTrue_Icon[];
	string $melListIconFalse[];
	string $melListIconFalse_Icon[];
	int $j=0;
	int $k=0;
	for($i=0; $i<size($melList); $i++){
		string $command = $melList[$i];
		if(endsWith($command,"Options"))continue;
		string $icon = AriScriptLauncher_IconExtension($command);
		if($icon != "commandButton.png"){
			$melListIconTrue[$j] = $melList[$i];
			$melListIconTrue_Icon[$j] = $icon;
			$j++;
		}
		else{
			$melListIconFalse[$k] = $melList[$i];
			$melListIconFalse_Icon[$k] = $icon;
			$k++;
		}
	}
	string $melListSort[]      = stringArrayCatenate($melListIconTrue, $melListIconFalse);
	string $melListSort_Icon[] = stringArrayCatenate($melListIconTrue_Icon, $melListIconFalse_Icon);
	deleteUI $AriScriptLauncher_UI_direCL;
	$AriScriptLauncher_UI_direCL = `columnLayout -p $AriScriptLauncher_UI_direSL -adj true`;
	for($i=0; $i<size($melListSort); $i++){
		string $command = $melListSort[$i];
		string $icon    = $melListSort_Icon[$i];
		int $optionTrue = false;
		string $options = $command+"Options";
		if(stringArrayContains ($options, $melList)){
			$optionTrue = true;
		}
		string $url="null";
		$url = getAriMelList($command);
		if($url=="null"){
			$url = urlcheck($command);
		}
		rowLayout -nc 3 -adj 3 -cw 2 22;
		iconTextButton -c $command -image1 $icon;
		if($optionTrue){
			iconTextButton -c $options -image1 "hsNothing.png";
		}
		else{
			text -l "";
		}
		columnLayout -adj true;
		textField -w 100 -ed false -text $command;
		rowLayout -nc 3;
		button -w 80 -h 20 -l "Shelf +" -c ("AriScriptLauncher_AddShell(\""+$command+"\",\""+$icon+"\","+$optionTrue+",\""+$url+"\")");
		if($url != "null")	button -w 80 -h 20 -l "Web" -c ("AriScriptLauncher_urlOpen(\""+$url+"\",false)")  ;
		setParent..;
		setParent..;
		setParent..;
		separator;
	}
	setParent..;
}
global proc AriScriptLauncher_DireOpen(int $mode){
	global string $AriScriptLauncher_UI_direTextF;
	global string $AriScriptLauncher_UI_iconTextF;
	string $path;
	if($mode == 1) $path = `textField -q -text $AriScriptLauncher_UI_direTextF`;
	if($mode == 2) $path = `textField -q -text $AriScriptLauncher_UI_iconTextF`;
	if(`filetest -d $path`){
		 system ("load " + $path);
	}
}
global proc AriScriptLauncher_DireDialog(int $mode){
	global string $AriScriptLauncher_UI_direTextF;
	global string $AriScriptLauncher_UI_iconTextF;
	string $path;
	if($mode == 1) $path = `textField -q -text $AriScriptLauncher_UI_direTextF`;
	if($mode == 2) $path = `textField -q -text $AriScriptLauncher_UI_iconTextF`;
	string $getPath[] = `fileDialog2 -dir $path -fm 3 -okc "OK"`;
	$getPath[0] = ($getPath[0]+"/");
	if($getPath[0]=="/") $getPath[0] = $path;
	if($mode == 1) textField -e -text $getPath[0] $AriScriptLauncher_UI_direTextF;
	if($mode == 2) textField -e -text $getPath[0] $AriScriptLauncher_UI_iconTextF;
	AriScriptLauncher_melList_Reload();
}
proc string UI_melListView(){
	global string $AriScriptLauncher_UI_direSL;
	global string $AriScriptLauncher_UI_direCL;
	$AriScriptLauncher_UI_direSL = `scrollLayout -cr true`;
	$AriScriptLauncher_UI_direCL = `columnLayout -adj true`;
	setParent;
	setParent;
	AriScriptLauncher_melList_Reload();
	return $AriScriptLauncher_UI_direSL;
}
proc string UI_direList(){
	global string $AriScriptLauncher_UI_direTextF;
	global string $AriScriptLauncher_UI_iconTextF;
	string $melDire  = `internalVar -userScriptDir`;
	string $iconDire = `internalVar -userBitmapsDir`;
	string $frameLay = `frameLayout -cll true -l ""`;
	columnLayout -adj true;
	rowLayout -nc 4 -adj 2;
	text -w 40 -l "Script";
	$AriScriptLauncher_UI_direTextF = `textField -ed false -text $melDire`;
	button -w 28 -h 20 -l ".." -c "AriScriptLauncher_DireDialog(1)";
	iconTextButton -w 28 -c "AriScriptLauncher_DireOpen(1)" -image1 "SP_DirOpenIcon.png";
	setParent..;
	rowLayout -nc 4 -adj 2;
	text -w 40 -l "Icon";
	$AriScriptLauncher_UI_iconTextF = `textField -ed false -text $iconDire`;
	button -w 28 -h 20 -l ".." -c "AriScriptLauncher_DireDialog(2)";
	iconTextButton -w 28 -c "AriScriptLauncher_DireOpen(2)" -image1 "SP_DirOpenIcon.png";
	setParent..;
	setParent..;
	setParent..;
	return $frameLay;
}
global proc AriScriptLauncher(){
	if((`window -ex  AriScriptLauncher`)==true)deleteUI AriScriptLauncher;
	window -tlb 1 -title "AriScriptLauncher"  -w 240 -h 400  AriScriptLauncher;
	string $form =`formLayout`;
	string $dire    = UI_direList();
	string $melList = UI_melListView();
	setParent..;
	formLayout -e
	-af $dire "left" 0
	-af $dire "right" 0
	-af $melList "left" 0
	-af $melList "right" 0
	-ac $melList "top" 0 $dire
	-af $melList "bottom" 0
	$form;
	showWindow;
}
