//--------------------------------------------------------------------------
//
// ScriptName : AriTransferPosition
// Contents   : オブジェクトの頂点位置を転送。
// Author     : Ari
// URL        : cgjishu.net
// Since      : 2017/04
// LastUpdate : 
// Note       : 
//               
//--------------------------------------------------------------------------



proc AriPolygonCounterIsCancelled(int $mode){
	global string $AriPCounter_progressBar;
	global string $gMainProgressBar;
	global string $AriPCounterCountStartBtn;
	global string $AriPCounterInfo;
	progressBar -edit -endProgress $gMainProgressBar;
	textField -e -text "中断" -bgc 1 0 0 $AriPCounterInfo;
	confirmDialog -title "Confirm" -message "中断しました"
		 -button "Yes" -defaultButton "Yes"
		 -cancelButton "No" -dismissString "No";
	waitCursor -state off;
	progressBar -edit -endProgress $gMainProgressBar;
	progressBar -e -pr 0 $gMainProgressBar;
	progressBar -e -pr 0 $AriPCounter_progressBar;	
	button  -en true -e  $AriPCounterCountStartBtn;
}
proc string[] AriTransferPosition_CircumferenceVer(string $verList[],int $mode){
	string $circumferenceList[];
	clear $circumferenceList;
	string $extendEdges[];
	if($mode==0)$extendEdges = `polyListComponentConversion -te $verList`;
	if($mode==1)$extendEdges = `polyListComponentConversion -tf $verList`;	
	string $extendVers[] = `polyListComponentConversion -tv $extendEdges`;
	$extendVers = `filterExpand -selectionMask 31 $extendVers`;
	$circumferenceList=stringArrayRemoveExact($verList, $extendVers);
	return $circumferenceList;
}
proc string[] AriTransferPosition_CircumferenceUV(string $verList[],int $mode){
	string $circumferenceList[];
	clear $circumferenceList;
	string $extendEdges[];
	if($mode==0){
		$extendEdges = `polyListComponentConversion -te $verList`;
	}
	if($mode==1)$extendEdges = `polyListComponentConversion -tf $verList`;	
	string $extendVers[] = `polyListComponentConversion -tuv $extendEdges`;
	$extendVers = `filterExpand -selectionMask 35 $extendVers`;
	$circumferenceList=stringArrayRemoveExact($verList, $extendVers);
	return $circumferenceList;
}
proc string[] AriTransferPosition_ArrayContainsArray(string $verListA[],string $verListB[]){
	string $ContainsList[];
	int $i=0;
	for($ver in $verListA){
		if(stringArrayContains($ver,$verListB)){
			$ContainsList[$i]=$ver;
			$i++;
		}
	}
	return $ContainsList;
}
global proc AriDebugPrint_float (string $text,float $val){
	print ($text+" "+$val+"\n");
}
proc string [] AriTransferPosition_GoSymmetryTP(string $UnSymmetry_plus[], string $UnSymmetry_minus[], vector $plus_pivPos, vector $minus_pivPos, int $UVMode, float $gosa){
	global string $AriTransferPositionSlider[8];
	global string $AriTransferPosition_message;
	global string $AriTransferPositionPC; 
	global string $gMainProgressBar;     
	int $UnSymmeBeforeTotal = size($UnSymmetry_plus);
	int $loop=`intField -q -v $AriTransferPositionSlider[3]`;
	$loop = $loop*2;
	text -e -label ("トポロジ確認中") -bgc 0.3 0.3 0.3 $AriTransferPosition_message;
	progressBar -edit -beginProgress -isInterruptable true -status "..." -maxValue 100 $gMainProgressBar;
	print ($UnSymmeBeforeTotal+"\n");
	print (size($UnSymmetry_minus)+"/n");
	progressBar -e -maxValue ($UnSymmeBeforeTotal) -pr 0 $AriTransferPositionPC ;
	progressBar -e -maxValue ($UnSymmeBeforeTotal) -pr 0 $gMainProgressBar;
	print("トポロジ------------------------\n");
	AriDebugPrint_float ("$UVMode",$UVMode);
	AriDebugPrint_float ("$gosa",$gosa);
	int $moveCounter=0;
	int $breakTrue = false; 
	int $loopVerTotal[2];
	int $ii;
	for($ii=0; $ii < $loop; $ii++){
		if($breakTrue == true)break;
		int $circumMode=($ii)%2;
		if(size($UnSymmetry_plus)==0)break;
		if($loopVerTotal[0]==$loopVerTotal[1] && $loopVerTotal[0]==size($UnSymmetry_plus))break;
		$loopVerTotal[$circumMode] = size($UnSymmetry_plus);
		string $extendVers_plus_num[]; 
		string $extendVers_minus_num[];
		if($UVMode==0){
			$extendVers_plus_num  = AriTransferPosition_CircumferenceVer($UnSymmetry_plus, $circumMode);
			$extendVers_minus_num = AriTransferPosition_CircumferenceVer($UnSymmetry_minus,$circumMode);
		}
		if($UVMode==1){
			$extendVers_plus_num  = AriTransferPosition_CircumferenceUV($UnSymmetry_plus, $circumMode);
			$extendVers_minus_num = AriTransferPosition_CircumferenceUV($UnSymmetry_minus,$circumMode);
		}
		vector $extendVers_plus_pos[];
		vector $extendVers_minus_pos[];
		clear $extendVers_plus_pos;
		clear $extendVers_minus_pos;
		for($i=0; $i<size($extendVers_plus_num); $i++){
			if($UVMode==0)$extendVers_plus_pos[$i] = `pointPosition -l $extendVers_plus_num[$i]`;
			if($UVMode==1){
				float $uvPosWork[2]=`polyEditUV    -q $extendVers_plus_num[$i]`;
				$extendVers_plus_pos[$i]=<<$uvPosWork[0],$uvPosWork[1],0>>;
			}
		}
		for($i=0; $i<size($extendVers_minus_num); $i++){
			if($UVMode==0)$extendVers_minus_pos[$i]=`pointPosition -l $extendVers_minus_num[$i]`;
			if($UVMode==1){
				float $uvPosWork[2]=`polyEditUV    -q $extendVers_minus_num[$i]`;
				$extendVers_minus_pos[$i]=<<$uvPosWork[0],$uvPosWork[1],0>>;
			}
		}
		string $extendVers_plus_sym[];
		string $extendVers_minus_sym[];
		clear $extendVers_plus_sym;
		clear $extendVers_minus_sym;
		int $symCount=0;
		for($i=0; $i<size($extendVers_plus_num); $i++){
			float $plus_pos[] = $extendVers_plus_pos[$i] - $plus_pivPos;
			for($j=0; $j<size($extendVers_minus_num); $j++){
				float $minus_pos[] = $extendVers_minus_pos[$j] - $minus_pivPos;
				if(AriTransferPosition_valMuch($plus_pos,$minus_pos,$gosa)){
					$extendVers_plus_sym[$symCount]=$extendVers_plus_num[$i];
					$extendVers_minus_sym[$symCount]=$extendVers_minus_num[$j];
					$symCount++;
					break;
				}
			}
		}
		string $extendVers_main_sym[];
		string $extendVers_sub_sym[];
		$extendVers_main_sym = $extendVers_plus_sym;
		$extendVers_sub_sym  = $extendVers_minus_sym;
		string $UnSymmetry_main[];
		string $UnSymmetry_sub[];
		$UnSymmetry_main = $UnSymmetry_plus;
		$UnSymmetry_sub  = $UnSymmetry_minus;
		string $newSym_main[];
		string $newSym_sub[];
		clear $newSym_main;
		clear $newSym_sub;
		int $k=0;
		for($i=0; $i<size($extendVers_sub_sym);$i++){
			if(`progressBar -q -ic $gMainProgressBar`){
				print("中断\n");
				text -e -label ("トポロジ確認 中断 " + $moveCounter + "/" + ($UnSymmeBeforeTotal) ) -bgc 1 0.5 0.5 $AriTransferPosition_message;
				$breakTrue = true;
				break;
			}
			string $extendVers_sub_sym_Array[1]={$extendVers_sub_sym[$i]};
			if($UVMode==0)$subOne_extendVers = AriTransferPosition_CircumferenceVer($extendVers_sub_sym_Array,$circumMode);
			if($UVMode==1)$subOne_extendVers = AriTransferPosition_CircumferenceUV ($extendVers_sub_sym_Array,$circumMode);
			string $exUnSymList[];
			$exUnSymList=AriTransferPosition_ArrayContainsArray($subOne_extendVers,$UnSymmetry_sub);
			if(size($exUnSymList)==1){
				progressBar -e -pr $moveCounter $AriTransferPositionPC ;
				progressBar -e -pr $moveCounter $gMainProgressBar;
				text -e -label ("トポロジ確認中 " + $moveCounter + "/" + ($UnSymmeBeforeTotal)) -bgc 0.3 0.3 0.3 $AriTransferPosition_message;
				$moveCounter++;
				string $subVer=$exUnSymList[0];
				string $extendVers_main_sym_Array[1];
				$extendVers_main_sym_Array[0]=$extendVers_main_sym[$i];
				string $mainOne_ExtendVers[];
				if($UVMode==0)$mainOne_ExtendVers = AriTransferPosition_CircumferenceVer($extendVers_main_sym_Array,$circumMode);
				if($UVMode==1)$mainOne_ExtendVers = AriTransferPosition_CircumferenceUV ($extendVers_main_sym_Array,$circumMode);
				string $exUnSymList[]=AriTransferPosition_ArrayContainsArray($mainOne_ExtendVers,$UnSymmetry_main);
				string $mainVer=$exUnSymList[0];
				float $pos[];
				if($UVMode==0)$pos=`pointPosition -l $mainVer`;
				if($UVMode==1)$pos=`polyEditUV -q $mainVer`;
				if($UVMode==0) move -ls ($pos[0]+$minus_pivPos.x-$plus_pivPos.x) ($pos[1]+$minus_pivPos.y-$plus_pivPos.y) ($pos[2]+$minus_pivPos.z-$plus_pivPos.z) $subVer;
				if($UVMode==1) polyEditUV -r false -u $pos[0] -v $pos[1] $subVer;
				$newSym_main[$k]=$mainVer;
				$newSym_sub[$k]=$subVer;
				$k++;
			}
		}
		$UnSymmetry_main=stringArrayRemoveExact($newSym_main, $UnSymmetry_main);
		$UnSymmetry_sub=stringArrayRemoveExact($newSym_sub, $UnSymmetry_sub);
		$UnSymmetry_plus  = $UnSymmetry_main;
		$UnSymmetry_minus = $UnSymmetry_sub;
		select $UnSymmetry_minus;
		progressBar -e -pr ($loop*100+($ii+1)*100) $AriTransferPositionPC ;
		progressBar -e -pr ($loop*100+($ii+1)*100) $gMainProgressBar;
		refresh;
	}
	if(!$breakTrue){
		int $UnSymmeTotal = $UnSymmeBeforeTotal-size($UnSymmetry_plus);
		text -e -label ($UnSymmeTotal+" 頂点を移動") $AriTransferPosition_message;
	}
	progressBar -e -endProgress $AriTransferPositionPC;
	progressBar -e -endProgress $gMainProgressBar;
	select -cl;
	return $UnSymmetry_minus;
}
global proc int AriTransferPosition_valMuch(float $valA[], float $valB[],float $gosa){
	int $muchTrue=0;
	if(    $valA[0] <= $valB[0]+$gosa && $valA[0] >= $valB[0]-$gosa
		&& $valA[1] <= $valB[1]+$gosa && $valA[1] >= $valB[1]-$gosa
		&& $valA[2] <= $valB[2]+$gosa && $valA[2] >= $valB[2]-$gosa){
		$muchTrue=1;
	}
	return $muchTrue;
}
global proc AriTransferPosition_GetVerPos(int $mode)
{
	global string $AriTransferPosition_message;
	global string $AriTransferPositionPC;
	global string $gMainProgressBar;
	global string $AriTransferPositionSlider[];
	global string $AriTransferPositionRadio[5];
	global string $AriTransferPositionOptionMenu[2];
	global string $AriTransferPositionTextField[2];
	global string $AriTraVer_sourceVer_num[]; 
	global vector $AriTraVer_sourceVer_pos[]; 
	global string $AriTraVer_sourceObjName;   
	global vector $AriTraVer_sourcePivPos;
	string $targetVer_num[];
	vector $targetVer_pos[];
	string $sourceVer_num[];
	vector $sourceVer_pos[];
	int $UVMode=0;
	float $gosa;
	float $range;
	int $moveMode = `optionMenu -q -select $AriTransferPositionOptionMenu[0]`;
	if($UVMode==0)	$range =`floatSliderGrp -q -v $AriTransferPositionSlider[1]`;
	if($UVMode==1)	$range =`floatSliderGrp -q -v $AriTransferPositionSlider[5]`;
	if($UVMode==0)	$gosa =`floatSliderGrp -q -v $AriTransferPositionSlider[0]`;
	if($UVMode==1)	$gosa =`floatSliderGrp -q -v $AriTransferPositionSlider[6]`;
	string $selects[]=`ls -sl`;
	string $selectVerList[];
	if($UVMode==0){
		$selectVerList = `polyListComponentConversion -tv $selects`;		
		$selectVerList = `filterExpand -selectionMask 31 $selectVerList`;
	}
	if($UVMode==1){
		$selectVerList = `polyListComponentConversion -tuv $selects`;		
		$selectVerList = `filterExpand -selectionMask 35 $selectVerList`;
	}
	if(size($selectVerList)<=0){
		print("オブジェクトまたは頂点を選択してください\n");
		return;
	}
	string $object[] = $selects;
	if(objectType($selects[0])!="transform"){
		$object = `polyListComponentConversion $selects`;		
		$object = `listRelatives -p -pa -type "transform" $object[0]`;
	}
	if($mode==0) $AriTraVer_sourceObjName = $object[0];
	vector $pivPos =<<0,0,0>> ;
	if($UVMode==0){
		float $scalePiv[]=`getAttr ($object[0]+".scalePivot")`;
		$pivPos =<<$scalePiv[0],$scalePiv[1],$scalePiv[2]>>;
		if($mode==0)$AriTraVer_sourcePivPos = $pivPos;
	}
	string $workVerList[] = $selectVerList;
	string $AllVertex[];
	if($mode==2){
		if($moveMode==1 || $moveMode==3){
			$workVerList = `polyListComponentConversion -tv $object[0]`;		
			$workVerList = `filterExpand -selectionMask 31 $workVerList`;
			$AllVertex = $workVerList;
		}
	}
	if($mode==0){
		clear $AriTraVer_sourceVer_num;
		clear $AriTraVer_sourceVer_pos;
	}
	int $i=0;
	for($ver in $workVerList){
		vector $posXYZ;
		if($UVMode==0)	$posXYZ = `pointPosition -l $ver`;	
		if($UVMode==1){
			$posXYZ = `polyEditUV -q $ver`;	
		}
		$posXYZ -= $pivPos;
		if($mode==0){
			$AriTraVer_sourceVer_num[$i] = $ver;
			$AriTraVer_sourceVer_pos[$i] = $posXYZ;
			$i++;
		}
		if($mode==1 || $mode==2){
			$targetVer_num[$i] = $ver;
			$targetVer_pos[$i] = $posXYZ;
			$i++;
		}
	}
	$sourceVer_num = $AriTraVer_sourceVer_num;
	$sourceVer_pos = $AriTraVer_sourceVer_pos;
	if($mode==0){
		print ("Get "+$AriTraVer_sourceObjName+"\n");
		textField -e -text $AriTraVer_sourceObjName $AriTransferPositionTextField[0];
		return;
	}
	text -e -label ( 0 +"/"+(size($targetVer_num)) ) -bgc 0.3 0.3 0.3 $AriTransferPosition_message;
	int $progressMaxVal=(size($targetVer_pos));
	if(size($targetVer_pos)>0)progressBar -e -maxValue $progressMaxVal $AriTransferPositionPC;
	progressBar -e
		-beginProgress
		-isInterruptable true
		$gMainProgressBar ;
	int $esc=1;
	string $sameTargetNum[];
	string $sameSourceNum[];
	string $unSameTarget_Num[];
	vector $unSameTarget_Pos[];
	string $unSameSource_Num[];
	vector $unSameSource_Pos[];
	int $samCounter=0;
	int $unSamCounter=0;
	int $breakTrue=false;
	string $resultSelectList[];
	string $distanceMoveList[];
	if($mode==1 || $moveMode==1 || $moveMode==3){
		int $searchloop=1;
		if($moveMode==3 && $mode==2)$searchloop=2;
		for($k=0;$k<$searchloop;$k++){
			clear $sameTargetNum;
			clear $sameSourceNum;
			clear $unSameTarget_Num;
			clear $unSameTarget_Pos;
			clear $unSameSource_Num;
			clear $unSameSource_Pos;
			for($targetCounter=0; $targetCounter<size($targetVer_num); $targetCounter++){	
				text -e -label ("探索中" + $targetCounter+"/"+(size($targetVer_pos)) ) $AriTransferPosition_message;
				progressBar -e -step 1 $AriTransferPositionPC ;
				if(`progressBar -query -isCancelled $gMainProgressBar`){
					$breakTrue = true;
					text -e -label ("探索 中断 "+$targetCounter+"/"+(size($targetVer_pos))) -bgc 1 0.5 0.5 $AriTransferPosition_message;
					break;
				}
				vector $targetPos = $targetVer_pos[$targetCounter];
				for($sourceCounter=0; $sourceCounter<size($sourceVer_num); $sourceCounter++){	
					vector $sourcePos = $sourceVer_pos[$sourceCounter];
					if( $targetPos.x <= $sourcePos.x+$gosa && $targetPos.x >= $sourcePos.x-$gosa &&
						$targetPos.y <= $sourcePos.y+$gosa && $targetPos.y >= $sourcePos.y-$gosa &&
						$targetPos.z <= $sourcePos.z+$gosa && $targetPos.z >= $sourcePos.z-$gosa){
						$sameTargetNum[$samCounter] = $targetVer_num[$targetCounter];
						$sameSourceNum[$samCounter] = $sourceVer_num[$sourceCounter];
						if($k==1 && $moveMode==3 && $mode==2){
							if(stringArrayContains($targetVer_num[$targetCounter],$selectVerList)){
								print ("距離移動実行"+$targetVer_num[$targetCounter]+"\n");
								if($UVMode==0){
									int $count = size($distanceMoveList);
									$distanceMoveList[$count] = $targetVer_num[$targetCounter];
									move -ls ($sourcePos.x+$pivPos.x) ($sourcePos.y+$pivPos.y) ($sourcePos.z+$pivPos.z) $targetVer_num[$targetCounter];
								}
								else{
								}
							}
						}
						$samCounter++;
						break;
					}
				}
			}
			$unSamCounter=0;
			$resultSelectCounter=0;
			for($i=0; $i<size($targetVer_num); $i++){		
				if(!stringArrayContains($targetVer_num[$i],$sameTargetNum)){
					$unSameTarget_Num[$unSamCounter] = $targetVer_num[$i];
					$unSameTarget_Pos[$unSamCounter] = $targetVer_pos[$i];
					$unSamCounter++;
					if(stringArrayContains($targetVer_num[$i],$selectVerList)){
						$resultSelectList[$resultSelectCounter] = $targetVer_num[$i];
						$resultSelectCounter++;
					}
				}
			}
			$unSamCounter=0;
			for($i=0; $i<size($sourceVer_num); $i++){		
				if(!stringArrayContains($sourceVer_num[$i],$sameSourceNum)){
					$unSameSource_Num[$unSamCounter] = $sourceVer_num[$i];
					$unSameSource_Pos[$unSamCounter] = $sourceVer_pos[$i];
					$unSamCounter++;
				}
			}
			if($moveMode==3){
				$targetVer_num = $unSameTarget_Num;
				$targetVer_pos = $unSameTarget_Pos;
				$sourceVer_num = $unSameSource_Num;
				$sourceVer_pos = $unSameSource_Pos;
				$gosa = $range;
			}
		}
		select $resultSelectList;
		select -d $distanceMoveList;
		text -e -label ( ($unSamCounter-2) +" 頂点 非同一座標") $AriTransferPosition_message;
	}
	if($mode==2 && $moveMode==2){
		print "頂点番号移動\n";
		string $targetVer_onlyNum[];
		string $sourceVer_onlyNum[];
		for($i=0; $i<size($targetVer_num); $i++){		
			string $sepa[];
			tokenize $targetVer_num[$i] "." $sepa;
			$targetVer_onlyNum[$i] = $sepa[1];
		}
		for($i=0; $i<size($sourceVer_num); $i++){		
			string $sepa[];
			tokenize $sourceVer_num[$i] "." $sepa;
			$sourceVer_onlyNum[$i] = $sepa[1];
		}
		for($targetCounter=0; $targetCounter<size($targetVer_num); $targetCounter++){		
			vector $targetPos = $targetVer_pos[$targetCounter];
			for($sourceCounter=0; $sourceCounter<size($sourceVer_num); $sourceCounter++){	
				if($targetVer_onlyNum[$targetCounter] == $sourceVer_onlyNum[$sourceCounter]){
					vector $sourcePos = $sourceVer_pos[$sourceCounter];
					if($UVMode==0) move -ls ($sourcePos.x+$pivPos.x)
					                        ($sourcePos.y+$pivPos.y)
					                        ($sourcePos.z+$pivPos.z) $targetVer_num[$targetCounter];
					break;
				}
			}
		}
	}
	progressBar -e -endProgress $AriTransferPositionPC;
	progressBar -e -endProgress $gMainProgressBar;
	if($mode==2 && $moveMode==1){
		if(size($unSameSource_Num)!=0){
			$i=0;
			$j=0;
			string $unSamTargetNumAll[];
			string $unSamTargetNumSelects[];
			vector $unSamTargetPosSelects[];
			for($unSametar in $unSameTarget_Num){
				string $workList[] = $selectVerList;
				if(stringArrayContains($unSametar,$workList)){
					$unSamTargetNumAll[$i] = $unSametar;
					$i++;
				}
				if(!stringArrayContains($unSametar,$selectVerList)){
					$unSamTargetNumSelects[$j] = $unSametar;
					if($UVMode==0)$unSamTargetPosSelects[$j]=`pointPosition -l $unSametar`;
					$j++;
				}
			}
			string $umMoveList[] = AriTransferPosition_GoSymmetryTP($unSameSource_Num, $unSamTargetNumAll, $AriTraVer_sourcePivPos, $pivPos, $UVMode, $gosa);
			for($j=0; $j<size($unSamTargetNumSelects); $j++){
				vector $pos = $unSamTargetPosSelects[$j];
				move -ls ($pos.x) ($pos.y) ($pos.z) $unSamTargetNumSelects[$j];
			}
			string $lastSelects[];
			$j=0;
			for($ver in $umMoveList){
				if(stringArrayContains($ver,$selectVerList)){
					$lastSelects[$j] = $ver;
					$j++;
				}
			}
			select $lastSelects;
		}
	}
}
global proc AriTransferPosition_UIChange(){
	global string $AriTransferPositionRadio[5];
	global string $AriTransferPositionGroups[4];
	global string $AriTransferPositionSlider[8];
	global string $AriTransferPositionOptionMenu[2];
	int $UVVer        = `radioButtonGrp -q -select $AriTransferPositionRadio[2]`;
	int $selectValMode = `optionMenu -q -select $AriTransferPositionOptionMenu[0]`;
	if($UVVer==1){
		floatSliderGrp -e -en 1 $AriTransferPositionSlider[0];
		floatSliderGrp -e -en 0 $AriTransferPositionSlider[6];
		floatSliderGrp -e -en 1 $AriTransferPositionSlider[1];
		floatSliderGrp -e -en 0 $AriTransferPositionSlider[5];
	}
	if($UVVer==2){
		floatSliderGrp -e -en 0 $AriTransferPositionSlider[0];
		floatSliderGrp -e -en 1 $AriTransferPositionSlider[6];
		floatSliderGrp -e -en 0 $AriTransferPositionSlider[1];
		floatSliderGrp -e -en 1 $AriTransferPositionSlider[5];
	}	
	int $mode[3];
	if($selectValMode==1){
		$mode[0]=1;
		$mode[1]=1;
		$mode[2]=0;
	}
	if($selectValMode==2){
		$mode[0]=0;
		$mode[1]=1;
		$mode[2]=1;
	}
	columnLayout -e -en $mode[0] $AriTransferPositionGroups[0];
	if($selectValMode==3){
		columnLayout -e -en true $AriTransferPositionGroups[2];
	}
	else{
		columnLayout -e -en false $AriTransferPositionGroups[2];
	}
}
global proc AriTransferPosition(){
	global string $AriTransferPosition_message;
	global string $AriTransferPositionPC;
	global string $AriTransferPositionSlider[8];
	global string $AriTransferPositionRadio[5];
	global string $AriTransferPositionGroups[4];
	global string $AriTransferPositionFloat[2];
	global string $AriTransferPositionOptionMenu[2];
	global string $AriTransferPositionTextField[2];
	string $mage;
	if((`window -ex AriTransferPosition`)==true)deleteUI AriTransferPosition;
	window -title "AriTransferPosition"  -w 300 -h 200 -mxb 0  AriTransferPosition;
	string $tabChild1=`columnLayout -adj 1`;
	rowLayout -h 30 -nc 2 -cw2 75 130 -vis false ;
		text -label "コンポーネント:";
		$AriTransferPositionRadio[2] = `radioButtonGrp -l "  "  -nrb 2  -labelArray2 "頂点" "UV" -select 1 -cw3 2 50 50 -cc "AriTransferPosition_UIChange()" `;
	setParent..;
	;
	separator -h 5 -w 240 -style "in";
	text -al "left" -label "探索許容値:";
	$AriTransferPositionSlider[0]=`floatSliderGrp -l "" -field true -cw 1 30 -min 0.0000 -max 0.01 -fmx 100 -value 0.001   -step 0.00001`;
	$AriTransferPositionSlider[6]=`floatSliderGrp -l "UV" -vis false  -field true -cw 1 30 -min 0.0000 -max 0.01 -fmx 10 -value 0.00001 -step 0.00001`;
	separator -h 5 -w 240 -style "in";
	rowLayout -nc 2 -cw2 140 130  ;
		text -label "移動方法:       ";
		$AriTransferPositionOptionMenu[0] = `optionMenu -w 140 -cc AriTransferPosition_UIChange -label "" `;
					menuItem -label "トポロジ";
					menuItem -label "頂点番号";
					menuItem -label "距離";
	setParent..;
	$AriTransferPositionGroups[0]=`columnLayout`;
		rowLayout -nc 2 -cw2 70 130;
		text -l "反復回数:";
		$AriTransferPositionSlider[3]=`intField -w 30 -v 50 -min 1 -max 100`;
		setParent..;
	setParent..;
	setParent..;
	$AriTransferPositionGroups[2]=`columnLayout -adj 1`;
		text -al "left" -label "移動近似値:";
		$AriTransferPositionSlider[1]=`floatSliderGrp -field true -l "" -cw 1 30 -min 0.001 -max 1 -value 0.01 -step 0.001 -fmx 1000`;
		$AriTransferPositionSlider[5]=`floatSliderGrp -field true -l "UV" -vis false -cw 1 30 -min 0.001 -max 1 -value 0.01 -step 0.001 -fmx 1000`;
	setParent..;
	$AriTransferPositionTextField[0] = `textField -ed false -text ""`;
	button  -label "Get" -h 30   -command ("AriTransferPosition_GetVerPos(0)");
	string $buttonL,$buttonR;
	string $form2 = `formLayout`;
	$buttonL = `button  -label "探索" -h 30   -command ("AriTransferPosition_GetVerPos(1)")`;
	$buttonR = `button  -label "移動" -h 30   -command ("AriTransferPosition_GetVerPos(2)")`;
	setParent..;
	formLayout -e
		-af $buttonL	"left" 0
		-ap $buttonL	"right" 0 50
		-af $buttonL	"bottom" 0 
		-ap $buttonR	"left" 0 50
		-af $buttonR	"right" 0
		-af $buttonR	"bottom" 0 
	$form2;
	$AriTransferPosition_message = `text -al "left" -label ""`;
	$AriTransferPositionPC= `progressBar -width 240`;
	setParent..;
	AriTransferPosition_UIChange();
	showWindow;
	optionMenu -e -sl 1 $AriTransferPositionOptionMenu[0];
	AriTransferPosition_UIChange();
}
